### ISSUE TITLE
Javascript diagnostics not displayed

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/lsp4ij#110]
This index.js file shows 2 errors:
```index.js
//@ts-check
export class Dog extends Animal {
    constructor(){
        super("Dog")
    }
    speak() {
        console.log(`I'm a ${this.name}'`)
    }
}

class Rectangle {
  constructor(height, width) {
    if (false) {
        console.log("nopee");
    }
    this.height = height;
    this.width = width;
  }
}
```

<img width="375" alt="Screenshot 2024-01-22 at 09 09 56" src="https://github.com/redhat-developer/lsp4ij/assets/148698/92c8d206-dcee-413c-83c3-f4fba02514e3">

Yet several diagnostics are published by the typescript LS:
```
[Trace - 09:02:34] Received notification ‘textDocument/publishDiagnostics’
Params: {
  “uri”: “file:///Users/fbricon/IdeaProjects/trigger-suggest/src/go/index.js”,
  “diagnostics”: [
    {
      “range”: {
        “start”: {
          “line”: 1,
          “character”: 25
        },
        “end”: {
          “line”: 1,
          “character”: 31
        }
      },
      “severity”: 1,
      “code”: 2304,
      “source”: “typescript”,
      “message”: “Cannot find name \u0027Animal\u0027.”
    },
    {
      “range”: {
        “start”: {
          “line”: 6,
          “character”: 34
        },
        “end”: {
          “line”: 6,
          “character”: 38
        }
      },
      “severity”: 1,
      “code”: 2339,
      “source”: “typescript”,
      “message”: “Property \u0027name\u0027 does not exist on type \u0027Dog\u0027.”
    },
    {
      “range”: {
        “start”: {
          “line”: 10,
          “character”: 6
        },
        “end”: {
          “line”: 10,
          “character”: 15
        }
      },
      “severity”: 4,
      “code”: 6196,
      “source”: “typescript”,
      “message”: “\u0027Rectangle\u0027 is declared but never used.”
    },
    {
      “range”: {
        “start”: {
          “line”: 11,
          “character”: 14
        },
        “end”: {
          “line”: 11,
          “character”: 20
        }
      },
      “severity”: 4,
      “code”: 7044,
      “source”: “typescript”,
      “message”: “Parameter \u0027height\u0027 implicitly has an \u0027any\u0027 type, but a better type may be inferred from usage.”
    },
    {
      “range”: {
        “start”: {
          “line”: 11,
          “character”: 22
        },
        “end”: {
          “line”: 11,
          “character”: 27
        }
      },
      “severity”: 4,
      “code”: 7044,
      “source”: “typescript”,
      “message”: “Parameter \u0027width\u0027 implicitly has an \u0027any\u0027 type, but a better type may be inferred from usage.”
    },
    {
      “range”: {
        “start”: {
          “line”: 13,
          “character”: 8
        },
        “end”: {
          “line”: 13,
          “character”: 29
        }
      },
      “severity”: 4,
      “code”: 7027,
      “source”: “typescript”,
      “message”: “Unreachable code detected.”
    }
  ]
}
```

If you put the cursor on L14, you do get a code action to remove the unreachable code though.

Could be the error mapping that ignores the severity.

**Comment by fbricon** [comment]
It's actually working as expected, LSP Hint is mapped to IJ Information:
https://github.com/redhat-developer/lsp4ij/blob/5407e6e5a97f7e388cd5b19258428aa47532699e/src/main/java/com/redhat/devtools/lsp4ij/operations/diagnostics/SeverityMapping.java#L48

which doesn't show anything
<img width="232" alt="Screenshot 2024-01-22 at 09 31 19" src="https://github.com/redhat-developer/lsp4ij/assets/148698/569cbb4f-130c-45b0-bdab-e8aed8bda8bd">

**Comment by angelozerr** [comment]
I wonder if we should create (I don't know if it is possible) our own `Hint` higlight? We could do like vscode with `...`

**Comment by fbricon** [comment]
We might simply align better with IJ's standards, i.e make LSP warnings as IJ warnings, instead of weak warnings, and keep information as week warnings.
The big difference is IJ warning are not underlined, but their background is filled in yellow

**Comment by angelozerr** [comment]
> The big difference is IJ warnings are not underlined, but their background is filled in yellow

Indeed and I found it is uglly. You have the impression that the element which is highlited as warn, is selected (LSP highlight).

**Comment by fbricon** [comment]
Works now:
 
<img width="737" alt="Screenshot 2024-02-19 at 18 27 24" src="https://github.com/redhat-developer/lsp4ij/assets/148698/ff1e437b-ecc0-4534-b756-830a6e67b03b">
