### ISSUE TITLE
Don't cancel the LSP response (from Java side) when ProcessCanceledException is thrown

### ISSUE THREAD

**Issue by mrglavas** [redhat-developer/lsp4ij#139]
I'm seeing this happen occasionally and have been able to reproduce this with both Liberty Tools for IntelliJ and Quarkus Tools that would be using recent versions of LSP4iJ. Instructions for reproducing and screenshots from both plug-ins are available here: https://github.com/OpenLiberty/liberty-tools-intellij/issues/648.

**Comment by angelozerr** [comment]
Could you share please your project  which causes this issue?

**Comment by mrglavas** [comment]
They're just projects generated from: https://start.microprofile.io/. I deleted the `@Liveness` annotation from the `ServiceLiveHealthCheck` class.
[quarkus-demo.zip](https://github.com/redhat-developer/lsp4ij/files/14272156/quarkus-demo.zip)
