### ISSUE TITLE
Promote the save settings in LSP console

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/lsp4ij#206]
When you update the server trace or other fields in the LSP console it requires to click on the Apply buton (Save icon) from the left toolbar:

![image](https://github.com/redhat-developer/lsp4ij/assets/1932211/2197e3e6-cf23-4871-86b0-8c87f44b8f87)

Even if it is explained here https://github.com/redhat-developer/lsp4ij user could not see this Apply button and could have the impression that it is bugged.

I think it should be nice to show something (a kind of notification or balloon) when a settings change to say to the user that it need to save the settings to apply them.

See https://github.com/OpenLiberty/liberty-tools-intellij/issues/718

//cc @mrglavas

**Comment by MituuZ** [comment]
I can try to handle this, was able to create the balloon, but still need to solve how to nicely handle the update calls as it is continuous and causes flickering.

Should the balloon just pop up once each time when changing the configuration from the initial values? e.g. not having a timeout and resetting when setting the values back to initial

**Comment by MituuZ** [comment]
Solved that issue and I feel like it is working as one could expect, created a PR for this: https://github.com/redhat-developer/lsp4ij/pull/209

**Comment by angelozerr** [comment]
It looks very nice!

The main idea with this issue is that when user starts using LSP4IJ LSP console settings, it should be know that. But when you know  that, it can be borring to have this balloon popup again and again.

I think we should have a link like `Got it` to close the popup and don't reopen the popup (to do that, we should store this info in a settings). To do that I suggest that you see a draft PR that I did to know where settings should be stored, see https://github.com/redhat-developer/lsp4ij/pull/198/files#diff-6658252c6e7949670e07b00eefa492e0b35ba35b45d58306db3ca83808ace233R257 

Perhaps we should have an UI preferences to reactivate this popup @fbricon what do you think about that?

> Still would need to fix the location to point to the correct element.

Your popup is displayed on `Apply` button location, it is good no?

> Should the balloon just pop up once each time when changing the configuration from the initial values? e.g. not having a timeout and resetting when setting the values back to initial.

The ballon should follow the same rule that enable of `Apply` button, it is to promote to the user "please click on Apply button".

Perhaps you could show the balloon here https://github.com/redhat-developer/lsp4ij/blob/75f8f0158bad9656f1247dee42d181581d8dc8f9/src/main/java/com/redhat/devtools/lsp4ij/console/actions/ApplyLanguageServerSettingsAction.java#L44 when balloon is never displayed and when language server view is modified.

**Comment by MituuZ** [comment]
Yes I managed to fix the balloon location, got the correct element and moved the x for 1/2 of its width to center it better on the icon itself.

I'll look into the settings, having the possibility to not have it pop up sounds good

**Comment by MituuZ** [comment]
There doesn't seem to be an existing settings class for plugin wide configurations, just language server specific if I'm not wrong.

Should that be a separate issue?

**Comment by angelozerr** [comment]
As I suggested you, please do like https://github.com/redhat-developer/lsp4ij/pull/198/files#diff-6658252c6e7949670e07b00eefa492e0b35ba35b45d58306db3ca83808ace233

In other words, you need to add a new field settings at https://github.com/redhat-developer/lsp4ij/blob/0247aac899c85cd69e773b8439b0d743f16aaf96/src/main/java/com/redhat/devtools/lsp4ij/settings/UserDefinedLanguageServerSettings.java#L225 

UserDefinedLanguageServerSettings is a bad name and because it exists too an another class with same name which is used for  user defined language server.

The `com.redhat.devtools.lsp4ij.settings.UserDefinedLanguageServerSettings` is the language server settings with project scope which contains today a Map field used to configure settings per language server. You need just to add a new field like I suggested.

> Should that be a separate issue?

I think it is important to have this settings to disable the balloon because it can be annoying to have this balloon if you know that you need to save.

**Comment by MituuZ** [comment]
Yeah the setting addition does make sense to me, I'm just thinking that it would then be language server specific?

e.g. you'd need to click the button for each language server to stop the balloon from showing instead of doing it once. 

Probably not a huge issue, as I doubt people have too many of them, but just wanted to make sure

**Comment by angelozerr** [comment]
> e.g. you'd need to click the button for each language server to stop the balloon from showing instead of doing it once.

I don't think son If you add your new field MY_NEW_FIELD like

```
public static class MyState {
        @Tag("state")
        @XCollection
        public Map<String, UserDefinedLanguageServerItemSettings> myState = new TreeMap<>();

       public boolean MY_NEW_FIELD;

        MyState() {
        }

    }
```

this settings is not per language server, it is a global settings (with project scope).

**Comment by MituuZ** [comment]
Ah, damn it. Yeah that makes sense :smile:

**Comment by MituuZ** [comment]
Implemented the button and settings handling. 

I had the value resetting when running the IDE with gradle. Maybe because of `runIde` task not persisting the settings correctly, or my value is MyState not initialized correctly

```
    public static class MyState {
        @Tag("state")
        @XCollection
        public Map<String, LanguageServerDefinitionSettings> myState = new TreeMap<>();

        MyState() {
        }

        private boolean isSaveTipBalloonDisabled = false;
    }
```
