### ISSUE TITLE
Log output cannot be done with a fresh workspace

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/lsp4ij#21]
I have a shortcoming where the log output would only show up once I restarted the IDE.

Steps:

ASSERT: have a clean build, Trace for Qute and Microprofile are off
EXEC: run the IDE and turn both to verbose in the settings
EXEC: open the "Language Servers" tool window
ASSERT: "Tools for Microprofile" is not running, no output is shown
EXEC: edit a java file and see if "Tools for Microprofile" is turned to "started" and see if there's log output
Result:
It doesnt turn to "started" and there's no log output for me. It only works as expected (steps above) once I restart the IDE.
Same is true for "Qute support" for me

See https://github.com/redhat-developer/intellij-quarkus/pull/849#pullrequestreview-1430980874

**Comment by fbricon** [comment]
@angelozerr is it still a problem today?

**Comment by angelozerr** [comment]
I have never seen this problem again. 

I close the issue.
