### ISSUE TITLE
Provide an Edit action to open the Language Server preferences

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/lsp4ij#211]
It would be nice to provide an Edit action like we have for Delete:

![image](https://github.com/redhat-developer/lsp4ij/assets/1932211/28a5db87-828b-4d3e-84c3-564e4fc4885d)

to open the preferences and select the proper language server:

![image](https://github.com/redhat-developer/lsp4ij/assets/1932211/6be018bf-eead-438a-a810-fba70cd1af3f)

@MituuZ are you interested to work on this issue?

**Comment by MituuZ** [comment]
Sure thing, I can take this on after completing #209 :+1:

**Comment by angelozerr** [comment]
> Sure thing, I can take this on after completing https://github.com/redhat-developer/lsp4ij/pull/209

Yes sure and I think you should fix your problem to start your Cobol LS too :)
