### ISSUE TITLE
Export user defined language server as JSON template file

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/lsp4ij#213]
Today we provide an hard coded template for some user defined language servers https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserDefinedLanguageServer.md#using-template

Those templates are declared in https://github.com/redhat-developer/lsp4ij/blob/main/src/main/resources/templates/template-ls.json and it contains some explanation, some configuration settings in a folder https://github.com/redhat-developer/lsp4ij/tree/main/src/main/resources/templates/rust-analyzer which uses the id https://github.com/redhat-developer/lsp4ij/blob/75f8f0158bad9656f1247dee42d181581d8dc8f9/src/main/resources/templates/template-ls.json#L255

It would be very nice if we could select several language servers show in the LSP console and export in a zip (template.json file + README + settings.json + initializationOptions.json) those language server.

It will give the capability to share the user defined language server that you have defined in your IJ with other people of your team.

@Mu

**Comment by angelozerr** [comment]
@MituuZ are you interested to work on this issue?

**Comment by MituuZ** [comment]
This does sound interesting, I can take a look. Might take a while though

**Comment by angelozerr** [comment]
> This does sound interesting,

Glad the idea please you. I think it could be intereting for yoru team to have this feature.

> I can take a look. Might take a while though

Yes sure no problem.
