### ISSUE TITLE
Adding a new LS should automatically make it start if matching documents are already opened

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/lsp4ij#215]
- open a typescript file
- add the typescript LS, set debug mode to verbose
- the typescript LS doesn't automatically start, unless you put the focus back to the .ts file

There should be a mechanism to loop through all opened editors et check if the newly added server matches their document

**Comment by fbricon** [comment]
See https://github.com/redhat-developer/lsp4ij/blob/0247aac899c85cd69e773b8439b0d743f16aaf96/src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinitionListener.java#L25

**Comment by angelozerr** [comment]
@MituuZ are you interested to work on this issue?

If yes don't hesitate to ping me if you need more informations. As @fbricon said to implement this issue, we need to use the existing listener  LanguageServerDefinitionListener loop for each opened editors and starts the language server if one editor matches the language server (it is just my first feeling perhaps it s more complicated)

**Comment by MituuZ** [comment]
Getting the editors shouldn't be hard, so it might be relatively simple. You can assign this to me, I'll get it to it later

**Comment by angelozerr** [comment]
Thanks @MituuZ !

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/lsp4ij/pull/262
