### ISSUE TITLE
Support for LSP `WorkspaceSymbols`

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/lsp4ij#22]
Part of the LSP protocol is [workspace symbols](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_symbol), which are a list of interesting parts of code that the user might want to navigate to quickly. For example, in lsp4mp, we have workspace symbols to represent JAX-RS endpoints.

It would be nice to provide a UI in intellij-quarkus to show these workspace symbols.

Here is a GIF of the workspace symbols UI in action in VS Code:
![workspace-symbols-rest-v2](https://user-images.githubusercontent.com/22376627/233079634-a3a8fd0e-494f-4d82-bd7b-c5c59b7039fc.gif)

**Comment by angelozerr** [comment]
Perhaps we could follow the same implementation than https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-intellij/src/main/java/robocorp/lsp/intellij/FeatureSymbols.java ?

**Comment by fbricon** [comment]
Unit tests are missing

**Comment by angelozerr** [comment]
> Unit tests are missing 

I dont know how to write tests. And I am super busy with Intellij Quarkus I have no time to write tests but sure I will do that (perhaps after the release of IJ quarkus)
