### ISSUE TITLE
Details pane in consoles view is not removed after deleting the last LS

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/lsp4ij#220]
I had the typescript ls defined and selected in the LSP consoles view, then deleted it. The details pane on the right was not removed
<img width="795" alt="Screenshot 2024-04-16 at 19 18 53" src="https://github.com/redhat-developer/lsp4ij/assets/148698/5ec48825-2136-46ca-b1fb-6690bb989404">

**Comment by angelozerr** [comment]
This usecase is when you have just one a LS definition that you remove. If you have several LS definition it should work, it select the first LS definition https://github.com/redhat-developer/lsp4ij/blob/4829a156059d8395f5c8cc27a1b161ddd202b6cf/src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorer.java#L84
