### ISSUE TITLE
Not compatible with IDEA 2024

### ISSUE THREAD

**Issue by AlexWeinstein92** [redhat-developer/lsp4ij#232]
I am using IDEA 2024.1 and am in the beginning stages of developing my LSP server using LSP4J. My team wants to ensure that the code is operative in IDEA before any further development on functionality that may have to be changed after learning lessons on integrating with plugin capabilities.

I could use an older version of IDEA for now if one is provided that is capable of using LSP4IJ. I would rather not switch to VSCode for testing because my team is much more comfortable with IDEA.

**Comment by fbricon** [comment]
I've tested LSP4IJ in IDEA 2024.1 and PyCharm 2024.1 and it works in both.
What errors do you get?

**Comment by fbricon** [comment]
The error message on the marketplace is misleading. I *think* this is caused by LSP4IJ not being released on the stable channel yet (should be done in 2-3 weeks)

<img width="1279" alt="Screenshot 2024-04-19 at 15 46 56" src="https://github.com/redhat-developer/lsp4ij/assets/148698/06143ca5-e92c-4a0a-b23e-0e538bbea134">

**Comment by AlexWeinstein92** [comment]
@fbricon thank you for noting this! I should have looked more closely at the docs too - I partially thought the warning you screenshotted was accurate because there is no marketplace plugin :) will try soon to install according to docs

@angelozerr thank you for the detailed guidance! Much appreciated 🙏 Wondering if you have any advice for specifically a Scala-based LSP4J LS? Not doing anything fancy in Scala here, but it is my preferred language

**Comment by fbricon** [comment]
We don't know scala at all, so don't expect any particular guidance there. 
https://github.com/scalameta/lsp-example might be useful for you, but seems you're already using lsp4j in your LS.

Now you can look at LSP4J usage in regular Java projects for inspiration. We've developed [a](https://github.com/eclipse/lemminx) [few](https://github.com/eclipse/lsp4mp/tree/master/microprofile.ls/org.eclipse.lsp4mp.ls) [of](https://github.com/redhat-developer/quarkus-ls/tree/master/qute.ls/com.redhat.qute.ls) [them](https://github.com/eclipse-jdtls/eclipse.jdt.ls).

**Comment by angelozerr** [comment]
As @fbricon said we have developped several language server in Java based on LSP4J like:

 * XML Language Server: https://github.com/eclipse/lemminx 
 * Qute Language Server: https://github.com/redhat-developer/quarkus-ls/tree/master/qute.ls
 * MicroProfile Language Server: https://github.com/eclipse/lsp4mp/tree/master/microprofile.ls
 
I don't know if you will use a parser like Antlr but if no,I suggest really that you use some classes that we have developped in https://github.com/eclipse/lemminx/tree/main/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/commons which provides for instance a [TextDocument](https://github.com/eclipse/lemminx/blob/main/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/commons/TextDocument.java) to manage cnversion between offset and position,etc

I had an idea to provide a library for https://github.com/eclipse/lemminx/blob/main/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/commons/ but we are very busy with LSP4IJ and [IntelliJ Quarkus](https://github.com/redhat-developer/intellij-quarkus).

**Comment by AlexWeinstein92** [comment]
The target language is a custom in-house language a working colleague has built for internal projects for our employer. It is called RIDDL, was created in Scala, and can be found at https://github.com/ossuminc/riddl

You can also see the LSP4JServer code I am working on here https://github.com/ossuminc/riddl-lsp

**Comment by AlexWeinstein92** [comment]
Update: getting errors trying to run my Scala-generated JAR using java in manual console. Advice would be appreciated :)
<img width="1662" alt="Screenshot 2024-04-24 at 12 33 02 PM" src="https://github.com/redhat-developer/lsp4ij/assets/105220856/6f85b316-98f7-405a-8972-d211805da7f9">
<img width="726" alt="Screenshot 2024-04-24 at 12 33 09 PM" src="https://github.com/redhat-developer/lsp4ij/assets/105220856/0a5a23f6-81ab-49e6-ae1b-65041e08f65e">

**Comment by angelozerr** [comment]
> Update: getting errors trying to run my Scala-generated JAR using java in manual console. 

@AlexWeinstein92 it seems you have deleted this comment.is it because you have resolved your problem?

If not it is because java is not accessible.

I suggest that you install last nightly build which should fix that because now when we start process we add environnent variables when process is created.

If it doesnt work I suggest that you try to write the command with the full path of java.

If it works I suggest that you add 

Sh or cmd before your java command like explained in environnent section at https://github.com/redhat-developer/lsp4ij/blob/main/docs%2FUserDefinedLanguageServer.md
