### ISSUE TITLE
support relative paths in the command and generate a config file in `.idea` that can be committed

### ISSUE THREAD

**Issue by DetachHead** [redhat-developer/lsp4ij#336]
for my use case, the language server will always be located at `.venv/scripts/basedpyright-langserver.exe` (on windows at least). ideally i would be able to just enter `basedpyright-langserver` as the command and it would pick it up from the current sdk:

![338075764-cf9e9649-e2ef-4767-8c0b-e4db84d9a672](https://github.com/redhat-developer/lsp4ij/assets/57028336/a22b42f1-565b-4855-a942-27c4daafd1bc)

specifying the full path works, but that's not ideal because i would like the language server to be saved in a config file that i can commit, so that others in my team can have the LSP configured automatically without them having to set it up themselves

**Comment by angelozerr** [comment]
I wonder if we fill the workspace directory with project root path, it will fix your issue.

Ifbit is working we should perhaps provide a New field working directory filled by défaut with the project root path.

@fbricon what do you think about that?

**Comment by KotlinIsland** [comment]
Inteliij has macro fields so this complexity is abstracted away

**Comment by angelozerr** [comment]
> Inteliij has macro fields so this complexity is abstracted away

Could you explain more your suggestion please.

**Comment by KotlinIsland** [comment]
![image](https://github.com/redhat-developer/lsp4ij/assets/65446343/7ad4d343-04e6-4b7c-91c1-c5a5e9e4993b)
(file watchers plugin)

So macro fields can contain pre-defined values that expand, this is great for shared config.

See: https://github.com/JetBrains/intellij-community/blob/master/platform/execution-impl/src/com/intellij/ide/macro/MacrosDialog.java

**Comment by angelozerr** [comment]
Thanks so much @KotlinIsland for your great idea. I didn't know this macro syntax and it is indeed a great idea.

I have created a PR for that at https://github.com/redhat-developer/lsp4ij/pull/340/files (with some documentation), hope you (and @DetachHead ) will like it

**Comment by angelozerr** [comment]
> specifying the full path works, but that's not ideal because i would like the language server to be saved in a config file that i can commit, so that others in my team can have the LSP configured automatically without them having to set it up themselves

You can now uses macro, see doc at at https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserDefinedLanguageServer.md#macro-syntax

**Comment by DetachHead** [comment]
awesome that works, thanks! only other thing is being able to commit the language server config. i will raise a separate issue for that
