### ISSUE TITLE
errors from language server do not appear

### ISSUE THREAD

**Issue by DetachHead** [redhat-developer/lsp4ij#338]
i can't seem to get the LSP to work at all:

# server config
![image](https://github.com/redhat-developer/lsp4ij/assets/57028336/bee42dc7-dd6e-403a-8441-ac42c9b6a7c2)

# mappings
not really sure how to use this. what is a language ID? tried the same thing in the "File type" tab with no luck.
![image](https://github.com/redhat-developer/lsp4ij/assets/57028336/db565cc4-1103-42f6-807a-752cc98e819b)

i also tried setting file name patterns, but i'm not sure if this is correct either. does it use glob syntax?
![image](https://github.com/redhat-developer/lsp4ij/assets/57028336/c722b0bd-cd62-40c9-abfa-0808b3ed902e)

# logs

it seems to have started the server:

![image](https://github.com/redhat-developer/lsp4ij/assets/57028336/1fe04cc6-c574-4d22-80d0-8b92c23dd239)

but it does not seem to be reporting any errors:

## expected result
(screenshot from the basedpyright vscode extension, which uses the LSP)
![image](https://github.com/redhat-developer/lsp4ij/assets/57028336/0fa225d3-4b94-464b-ba53-98f16752c85b)

## actual result
(this error is from pycharm's native python type checking, not the language server)
![image](https://github.com/redhat-developer/lsp4ij/assets/57028336/4870868e-eeaa-4e7d-a25b-f7561b003446)

**Comment by angelozerr** [comment]
> but it does not seem to be reporting any errors:

The log tab is filled with lsp window/logMessage 

You need to go to traces tab to see lsp traces and you should see some textDocument/publishDiagnostic if your ls reports some validation error

**Comment by angelozerr** [comment]
@DetachHead for your questions about language id, file type pattern etc please read https://github.com/redhat-developer/lsp4ij/blob/main/docs%2FUserDefinedLanguageServer.md

If it is not clear please tell me to omprove the documentation

**Comment by fbricon** [comment]
I tried it on Intellij IDEA and didn't get any validation at first, but then I added an empty configuration object `{}` and it just worked:
<img width="408" alt="Screenshot 2024-06-10 at 10 54 32" src="https://github.com/redhat-developer/lsp4ij/assets/148698/f55f3f23-84be-4cf2-b9e3-a168f72fd705">

<img width="455" alt="Screenshot 2024-06-10 at 10 54 11" src="https://github.com/redhat-developer/lsp4ij/assets/148698/29baefe2-b9e2-422f-b7d7-834b2074281f">

<img width="924" alt="Screenshot 2024-06-10 at 10 56 58" src="https://github.com/redhat-developer/lsp4ij/assets/148698/745ba2f7-a0a0-4e47-a33b-f54c43cf93fb">

**Comment by angelozerr** [comment]
That's very strange, because this didChangeConfiguration is used only when you save it, not when you start the ls.

I wonder if it isworking if you restart the ls?

**Comment by DetachHead** [comment]
> for your questions about language id, file type pattern etc please read https://github.com/redhat-developer/lsp4ij/blob/main/docs%2FUserDefinedLanguageServer.md
> 
> If it is not clear please tell me to omprove the documentation

my bad, looking into it further i realize language ID is an LSP feature: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentItem

perhaps the documentation could be updated to clarify this. i imagine many people attempting to use this plugin may be unfamiliar with the LSP protocol itself and are just trying to get their IDE to work well with the language they're using.

> I tried it on Intellij IDEA and didn't get any validation at first, but then I added an empty configuration object `{}` and it just worked

setting the empty config object works, thanks! should that field default to an empty object when it's not set? or maybe this is a bug with pyright's language server rather than this plugin?

**Comment by fbricon** [comment]
languageId should be a combobox with a list of preset languages eventually

**Comment by fbricon** [comment]
Fixed with #339. An empty configuration object is now always sent in `workspace/didChangeConfiguration` events on startup.

**Comment by angelozerr** [comment]
> my bad, looking into it further i realize language ID is an LSP feature: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentItem

> perhaps the documentation could be updated to clarify this. i imagine many people attempting to use this plugin may be unfamiliar with the LSP protocol itself and are just trying to get their IDE to work well with the language they're using.

See doc at https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserDefinedLanguageServer.md#language-id
