### ISSUE TITLE
LSP Plugin start error

### ISSUE THREAD

**Issue by CppCXY** [redhat-developer/lsp4ij#345]
I always get a startup error:
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/fe126d4d-ad16-4197-b7f1-1919e8a1cb1e)
cause by:
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/bbe8f2c5-4646-4197-8896-c8a66c2e4eac)
this my plugins.xml
```xml
  <extensions defaultExtensionNs="com.redhat.devtools.lsp4ij">
      <server id="SumnekoLua"
              name="Sumneko"
              factoryClass="com.cppcxy.ide.lsp.LspFactory">
          <description><![CDATA[
              <p>Sumneko Lua</p>
  ]]>
          </description>
      </server>
      <languageMapping language="Lua"
                       serverId="SumnekoLua"/>
  </extensions>
```

**Comment by angelozerr** [comment]
Have you this error only with nightly build or with 0.0.1 release too?

**Comment by angelozerr** [comment]
Have you this error only with nightly build or with 0.0.1 release too?

Could you share your pr please?

**Comment by CppCXY** [comment]
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/1c47db61-70af-48bb-b328-7d06f05bee84)
From the picture it looks like I'm using 0.0.1, but I manually updated to 0.0.2. 
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/22c32909-1e95-4c5a-a31b-372b0d6255d0)
but since this is 0.0.1, it will revert to 0.0.1 every time my debug. 
How can I set 0.0.2?
here is the [project](https://github.com/CppCXY/Intellij-SumnekoLua)

**Comment by angelozerr** [comment]
It should work with 0.0.1 too.

Let me try your project.

**Comment by CppCXY** [comment]
lsp4ij send rootPath endwith '/':
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/5406cd38-0cb7-4ada-8b05-26fd287c4be6)
jetbrain lsp send rootPath not with '/'
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/e8692f7a-4240-41d3-a53a-3601606a0d93)
this(end with '/') casuse sumneko lua can not work.

**Comment by angelozerr** [comment]
I cannot understand it seems your language server can be started now? Have you fixed your original error?

**Comment by CppCXY** [comment]
> I cannot understand it seems your language server can be started now? Have you fixed your original error?
I didn't do any fixing, I just skipped the exception, because the exception doesn't affect my normal startup.

**Comment by fbricon** [comment]
Can you provide a full stacktrace of the error (without skipping the exception)?
Are you sure that the ending slash is causing it?

**Comment by CppCXY** [comment]
I'm sorry, I may not have made my questions clear. Actually, there are two issues. The first one is that a pop-up appears every time I debug. The second one is that after skipping the exception, the language server functionality in the opened IDEA instance is not quite normal. This might be due to a problem with the format of the workspace path. We have integrated the JetBrains LSP before, and this issue did not occur.
I can't provide the stack trace because it doesn't appear in the IDEA's log. I can only provide it in the form of a screenshot:
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/c9f1666e-f77a-4123-a948-7e6401628d88)
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/a7c4c6c0-4be6-40a1-83ec-56ba71620284)
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/98bae285-2a2e-464e-a76a-03dccec38e28)

**Comment by fbricon** [comment]
There's an open bug about the LUA server [ignoring the Client capability configuration](https://github.com/LuaLS/lua-language-server/issues/2318)

**Comment by CppCXY** [comment]
Thanks, I'll ask the author to take care of this as soon as possible.
but due to the ending slash, it can not work normal, and I find out that rootPath also has the leading slash:
```
  rootPath = "/C:/Users/zc/Desktop/learn/",
  rootUri = "file:///C:/Users/zc/Desktop/learn/",
  trace = "off",
  workspaceFolders = { {
      name = "learn",
      uri = "file:///C:/Users/zc/Desktop/learn/"
    } }
```

**Comment by angelozerr** [comment]
@CppCXY I have created a PR to support configuration https://github.com/redhat-developer/lsp4ij/pull/346

**Comment by fbricon** [comment]
I got the lua server working fine with #346 on Mac, the slashes may not be an issue. Please try to manually install the [LSP4IJ-0.0.2-SNAPSHOT](https://github.com/redhat-developer/lsp4ij/actions/runs/9480917967/artifacts/1593308503) file from https://github.com/redhat-developer/lsp4ij/actions/runs/9480917967.

**Comment by fbricon** [comment]
@CppCXY I found a real problem with lua on IntelliJ though, but it's unrelated to LSP4IJ or the Lua LSP itself, it's probably coming from your own lua parser: any file containing things like `---@diagnostic disable: lowercase-global` will cause Intellij to report an error:

<img width="1047" alt="Screenshot 2024-06-12 at 13 57 41" src="https://github.com/redhat-developer/lsp4ij/assets/148698/6c1168e0-c2de-434f-9d88-eb4670a3c204">

**Comment by CppCXY** [comment]
> I got the lua server working fine with #346 on Mac, the slashes may not be an issue. Please try to manually install the [LSP4IJ-0.0.2-SNAPSHOT](https://github.com/redhat-developer/lsp4ij/actions/runs/9480917967/artifacts/1593308503) file from https://github.com/redhat-developer/lsp4ij/actions/runs/9480917967.

Thanks, I tried, but it still doesn't work, I know very well that it doesn't really read the data in the workspace, it reinterprets learn/ as learn/learn, see the log:
```
[20:00:52.152][warn] [#0:script\files.lua:111]: Fix real file uri: file:///c%3A/Users/zc/Desktop/learn/ -> file:///c%3A/Users/zc/Desktop/learn/learn
[20:00:52.152][info] [#0:script\workspace\workspace.lua:48]: Workspace create: 	file:///c%3A/Users/zc/Desktop/learn/learn
```
I know it's true that luals itself has processing problems, but it still works fine on other platforms like neovim.

**Comment by fbricon** [comment]
Then it might be a windows specific issue, as I said, everything's fine on Mac. We need to check on windows

**Comment by fbricon** [comment]
I didn't install emmylua

**Comment by CppCXY** [comment]
I mean my intellij-sumnekolua its analyzing front-end is come from emmylua

**Comment by angelozerr** [comment]
> I always get a startup error:

I created a PR for that https://github.com/redhat-developer/lsp4ij/pull/347

> Thanks, I tried, but it still doesn't work, I know very well that it doesn't really read the data in the workspace, it reinterprets learn/ as learn/learn, see the log:

I'm studying the problem.

**Comment by fbricon** [comment]
I tested the latest build from our main branch (https://github.com/redhat-developer/lsp4ij/actions/runs/9484891140) on a Windows 11 VM. The plugin starts, I don't see any issues with a trailing slash in the rootPath
<img width="472" alt="Screenshot 2024-06-12 at 17 58 35" src="https://github.com/redhat-developer/lsp4ij/assets/148698/ad56a57b-85ac-40fe-b3e0-f79f507d263b">


<img width="1482" alt="Screenshot 2024-06-12 at 17 54 40" src="https://github.com/redhat-developer/lsp4ij/assets/148698/c607db1f-a422-452e-bc25-4547352f3684">

**Comment by CppCXY** [comment]
> I tested the latest build from our main branch (https://github.com/redhat-developer/lsp4ij/actions/runs/9484891140) on a Windows 11 VM. The plugin starts, I don't see any issues with a trailing slash in the rootPath <img alt="Screenshot 2024-06-12 at 17 58 35" width="472" src="https://private-user-images.githubusercontent.com/148698/339045086-ad56a57b-85ac-40fe-b3e0-f79f507d263b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDQyMDYsIm5iZiI6MTcxODI0MzkwNiwicGF0aCI6Ii8xNDg2OTgvMzM5MDQ1MDg2LWFkNTZhNTdiLTg1YWMtNDBmZS1iM2UwLWY3OWY1MDdkMjYzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMTU4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTNiN2JmNmI5ZmVjNDNhZDBlZjU1MTFmNDg3Yzg5NDExZGE4NDg5NTNlMzI1OTE5ZDc0NzVmY2ZjMzgyY2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1O3V5cqsNXeUpaVniVHSxj3GrGo53afqk-w27esM7lA">
> 
> <img alt="Screenshot 2024-06-12 at 17 54 40" width="1482" src="https://private-user-images.githubusercontent.com/148698/339044873-c607db1f-a422-452e-bc25-4547352f3684.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDQyMDYsIm5iZiI6MTcxODI0MzkwNiwicGF0aCI6Ii8xNDg2OTgvMzM5MDQ0ODczLWM2MDdkYjFmLWE0MjItNDUyZS1iYzI1LTQ1NDczNTJmMzY4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMTU4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzE0OWI0ZWNiZTFlMzNkODI4ZTI2ODg2YzYyYzk0NWIxMzEzNGM4MGU3MmM4NjJjNjZiZGFlMDNjZmMxZDI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rPm0v-DnoMYzsB8te03v7Lkjd8JqxnVhPofIptSXghs">

It actually doesn't get anything from the workspace, you can't get hints from other files and it can't read the .luarc.json file in the workspace. for example, if you choose to quick fix and disable a diagnostic in the workspace, it will completely fail.

**Comment by angelozerr** [comment]
@CppCXY I have tried your plugin on Windows OS and it seems working, I have completion, higlight, quick fixes etc.

The quickfix which doesn't work is the following:

![image](https://github.com/redhat-developer/lsp4ij/assets/1932211/4927e6bb-fb26-43d5-bff7-09b4265f1246)


When I apply it, I have the error message:

![image](https://github.com/redhat-developer/lsp4ij/assets/1932211/6fb01c1b-ea05-4df6-a806-9d7a2794362f)

When you say "fail", is it this problem?

Have you completion, higlight which is working?

**Comment by CppCXY** [comment]
> Have you completion, higlight which is working?

highlighting is not a feature of the language server, it's handled by the PSI system of JetBrains that I'm using.
as for completion, it doesn't provide completions from other files in the current workspace.
> @CppCXY I suggest that you use LSP console to track LSP messages https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserGuide.md#lsp-console

LuaLs has owner log file, see:
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/0d996667-e991-4e3a-91fa-f7a1b5b17806)

I can see the log about workspace:
```log
[15:16:37.834][info] [#0:script\workspace\workspace.lua:38]: Workspace init root: 	file:///C:/Users/zc/Desktop/learn/
[15:16:37.834][info] [#0:script\workspace\workspace.lua:42]: Log path: 	C:/Users/zc/AppData/Roaming/JetBrains/IntelliJIdea2024.1/plugins/Sumneko-Lua/server/win32-x64/log/file_C_Users_zc_Desktop_learn_.log
[15:16:37.868][warn] [#0:script\files.lua:111]: Fix real file uri: file:///c%3A/Users/zc/Desktop/learn/ -> file:///c%3A/Users/zc/Desktop/learn/learn
[15:16:37.868][info] [#0:script\workspace\workspace.lua:48]: Workspace create: 	file:///c%3A/Users/zc/Desktop/learn/learn
```
due to the bug in luals, it incorrectly locates xx/learn/ to xx/learn/learn, so its analysis of the workspace actually failed, but I noticed that the rootPath sent by both the Jetbrains LSP client and the VSCode LSP client does not contain an ending slash.

>[Trace - 09:08:32] Received notification 'window/showMessage'
> Params: {
>  "type": 2,
>  "message": "Failed to modify settings\n\nPlease modify following settings manually:\n* `Lua.diagnostics.disable`: add 
> element `\"undefined-global\"` ;\n"
>}

the reason for this error is that LuaLS has analyzed a non-existent directory and it cannot create a configuration file there.

so, do we need to handle the ending slash?

**Comment by fbricon** [comment]
Do you have a sample project we can test?

**Comment by angelozerr** [comment]
> the reason for this error is that LuaLS has analyzed a non-existent directory and it cannot create a configuration file there.
   so, do we need to handle the ending slash?

IMHO I think Lua LS should take care of that, but I created the following PR https://github.com/redhat-developer/lsp4ij/pull/348
which fixes the problem and the Quickfix (workspace) works now perfectly on Windows OS and generate the .lua.json file.

I fixed rootUri and rootPath but the problem was not enough. I had to do the same fix on WorkspaceFolder uri andnow it is working pretty well.

**Comment by CppCXY** [comment]
> > the reason for this error is that LuaLS has analyzed a non-existent directory and it cannot create a configuration file there.
> > so, do we need to handle the ending slash?
> 
> IMHO I think Lua LS should take care of that, but I created the following PR #348 which fixes the problem and the Quickfix (workspace) works now perfectly on Windows OS and generate the .lua.json file.
> 
> I fixed rootUri and rootPath but the fix was not enough. I had to do the same fix on WorkspaceFolder uri and now it is working pretty well with my Windows OS!

Thanks!

**Comment by angelozerr** [comment]
> here the test project, when I install my plugin and open this project for the first time, I can't get completions here.

It is working for me on my Windows OS:

![image](https://github.com/redhat-developer/lsp4ij/assets/1932211/9f58245b-7b47-49de-9de0-6d924323d418)

**Comment by CppCXY** [comment]
> > here the test project, when I install my plugin and open this project for the first time, I can't get completions here.
> 
> It is working for me on my Windows OS:
> 
> ![image](https://private-user-images.githubusercontent.com/1932211/339280690-9f58245b-7b47-49de-9de0-6d924323d418.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjczNzgsIm5iZiI6MTcxODI2NzA3OCwicGF0aCI6Ii8xOTMyMjExLzMzOTI4MDY5MC05ZjU4MjQ1Yi03YjQ3LTQ5ZGUtOWRlMC02ZDkyNDMyM2Q0MTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMDgyNDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUyZmVkYTM2YjFmZTUxODE0ZmI1MjM3OTA3MDVhYjQyMTcxMmVmYjRlMGEwMzc2YmU0YTdkMDVhMWE2MDBmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2JUFlPeAqRn9HlWzuSBItQSVYbRRDTghNoXWJOMZE4w)
> 
> Coud you enable LSP console as verbose and share your LSP traces please.
> 
> In my case I see:
> 
> ![image](https://private-user-images.githubusercontent.com/1932211/339281422-8d4ab83e-1c62-4201-ab3e-faa11e800126.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjczNzgsIm5iZiI6MTcxODI2NzA3OCwicGF0aCI6Ii8xOTMyMjExLzMzOTI4MTQyMi04ZDRhYjgzZS0xYzYyLTQyMDEtYWIzZS1mYWExMWU4MDAxMjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMDgyNDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTEwNjBkMDBjYzk1ZmQ1YmRiOTA5ZDYwMDYyM2Q0MWYzYWJmNjYyYTJlZmQ4MjMzNTY4MDEwZDA4MzM2OGNhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o-Tw2Op29oAxS_62rSz0DHmYhgRZMdUMjSxkNVs7Vbo)

it's a windows only problem. this problem should no longer exist after you fix it

**Comment by angelozerr** [comment]
> it's a windows only problem. this problem should no longer exist after you fix it

You mean that my fix which removes '/' fixes your issue with completion? If it that I have tested without my PR and it is working too.

**Comment by fbricon** [comment]
@CppCXY please try https://plugins.jetbrains.com/plugin/23257-lsp4ij/versions/nightly/555671?noRedirect=true it should work much better on windows

**Comment by CppCXY** [comment]
> @CppCXY please try https://plugins.jetbrains.com/plugin/23257-lsp4ij/versions/nightly/555671?noRedirect=true it should work much better on windows

thanks, it work well. 
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/ddf51aeb-5945-4855-b4eb-fe0c4d6f15cc)

I have another question. Currently, I can't find references by using Ctrl + left mouse click. JetBrains LSP has already supported using "Find Usage" for references in 2024.5 EAP.  But I found that this plugin is implemented in goto/LSP references.

**Comment by angelozerr** [comment]
> I have another question. Currently, I can't find references by using Ctrl + left mouse click. JetBrains LSP will support using "Find Usage" for references in 2024.2 EAP 5. But I found that this plugin is implemented in goto/LSP references.

See doc at https://github.com/redhat-developer/lsp4ij/blob/main/docs/LSPSupport.md#references

**Comment by angelozerr** [comment]
> does the language server need to support all these features?

not all, just one

**Comment by CppCXY** [comment]
> > does the language server need to support all these features?
> 
> not all, just one
> 
> But as you are using custom FileType, I think it will not work.

![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/41b49257-2135-47b0-9849-ae863ebda4c2)
I have indeed implemented at least one of them here, and also defined the fileType, so I can't see Find Usage.

**Comment by angelozerr** [comment]
> I have indeed implemented at least one of them here, and also defined the fileType, so I can't see Find Usage.

Let me try finding a solution...

**Comment by fbricon** [comment]
@CppCXY please open a new ticket about find references, now that your plugin starts working with LSP4IJ
