### ISSUE TITLE
`rootUri` is not a project root path

### ISSUE THREAD

**Issue by seachicken** [redhat-developer/lsp4ij#354]
When the language server [intellij-inga](https://github.com/seachicken/intellij-inga) I'm developing receives an initialize request, the `rootUri` is not the project root path.

Here is the trace log.

actual:

```
[Trace - 09:34:49] Sending request 'initialize - (1)'.
Params: {
  "processId": 12721,
  "rootPath": "/Users/seito/git/GitHub/intellij-inga/src/main/",
  "rootUri": "file:///Users/seito/git/GitHub/intellij-inga/src/main/",
  ...
}
```

expected:

```
[Trace - 09:34:49] Sending request 'initialize - (1)'.
Params: {
  "processId": 12721,
  "rootPath": "/Users/seito/git/GitHub/intellij-inga/",
  "rootUri": "file:///Users/seito/git/GitHub/intellij-inga/",
  ...
}
```

Am I missing some setting? Please let me know if you know anything.

**Comment by angelozerr** [comment]
Which version are you testing? 0.0 1 which is released or the nighty build?

Please try with nighty build.

**Comment by seachicken** [comment]
I tried from 0.0.1. But I am trying 0.0.2-20240614-013035 now, and it seems solved. thank you!

result:

```
[Trace - 14:09:13] Sending request 'initialize - (1)'.
Params: {
  "processId": 12141,
  "rootPath": "/Users/seito/git/GitHub/intellij-inga",
  "rootUri": "file:///Users/seito/git/GitHub/intellij-inga",
```

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/lsp4ij/pull/348
