### ISSUE TITLE
Render diagnostic tag unnecessary

### ISSUE THREAD

**Issue by CppCXY** [redhat-developer/lsp4ij#355]
When rendering diagnostics in VS Code, if the 'tag' field of the diagnostic includes 'unnecessary', the color will be lightened. In JetBrains, it will be grayed out, but here it is underlined.

in vscode:
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/1d927c1d-5ee6-42b3-be1d-d7145d431e1c)

in lsp4ij:
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/fe27478e-22be-436d-ad7f-43f8a9cd8a4a)

**Comment by angelozerr** [comment]
I created a PR https://github.com/redhat-developer/lsp4ij/pull/357 to support that.

**Comment by CppCXY** [comment]
Thanks!
