### ISSUE TITLE
[feat] Support diagnostic tag deprecated

### ISSUE THREAD

**Issue by CppCXY** [redhat-developer/lsp4ij#358]
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/207870c3-a3e6-4c73-a0b0-d8b6cac81e0b)
the function 'f' should be strikethrough rendering  when called.

**Comment by fbricon** [comment]
#357 gives you this:
<img width="179" alt="Screenshot 2024-06-14 at 11 11 29" src="https://github.com/redhat-developer/lsp4ij/assets/148698/3c74b3e4-1041-42da-b7f9-9c6a539d6fe9">
