### ISSUE TITLE
[feat] Support to customize icon completion

### ISSUE THREAD

**Issue by CppCXY** [redhat-developer/lsp4ij#362]
in jetbrain LSP and vscode, it use file icon for file kind:
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/1e3e43c1-8c0f-433d-9f51-fd4a97260561)

but lsp4ij without icon:
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/cd6d2feb-533a-43f4-84df-1754db4ac156)

**Comment by angelozerr** [comment]
> but lsp4ij without icon:

If you screenshot, it uses an another file icon from Jetbrains, but there is an icon

We did that at:

https://github.com/redhat-developer/lsp4ij/blob/d4d186ddac757ba121777aa5468bebc1b9e9abda/src/main/java/com/redhat/devtools/lsp4ij/ui/IconMapper.java#L143

If you have a better icon please create a PR.

**Comment by CppCXY** [comment]
I remembered incorrectly, I customized the icon in JetBrains LSP. So, can LSP4IJ customize icons?
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/17591444-0899-4737-bcdd-d591bf83631d)

**Comment by angelozerr** [comment]
No it is not possible. 

We need to provide this support.

**Comment by angelozerr** [comment]
@CppCXY I target this issue for 0.0.3 since we want to create the release as soon as https://github.com/redhat-developer/lsp4ij/pull/360 will be merged.

Please create a lot of issues i you need to customize another thing to provide the best customization API. Thanks!

**Comment by CppCXY** [comment]
> @CppCXY I target this issue for 0.0.3 since we want to create the release as soon as #360 will be merged.
> 
> Please create a lot of issues i you need to customize another thing to provide the best customization API. Thanks!

Thanks, I will release my plugin after you release version 0.0.2. At that time, quite a few people should experience this plugin.

**Comment by angelozerr** [comment]
> Thanks, I will release my plugin after you release version 0.0.2. At that time, quite a few people should experience this plugin.

That's great!

If you like LSP4IJ, could you please:

 * add your review at https://plugins.jetbrains.com/plugin/23257-lsp4ij/edit/reviews to help us to promote LSP4IJ
 * create a PR to add your plugin at https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#who-is-using-lsp4ij

More we will have LSP4IJ IJ plugin, more we could have contributor and provide the best LSP support for IntelliJ.

**Comment by fbricon** [comment]
While this doesn't fully cover this request, #365 at least allows to show lua (and others) file completion with the proper icons.

**Comment by angelozerr** [comment]
See doc at https://github.com/redhat-developer/lsp4ij/blob/main/docs/LSPApi.md#lsp-completion-feature

**Comment by angelozerr** [comment]
See https://github.com/redhat-developer/lsp4ij/blob/main/docs/LSPApi.md#lsp-completion-feature and overrides getIcon method.
