### ISSUE TITLE
completion highlighted

### ISSUE THREAD

**Issue by CppCXY** [redhat-developer/lsp4ij#367]
The first option in the completion bar is not highlighted.
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/472f786d-3d33-47f7-a3e0-d1339123d550)
The second completion item is only highlighted when I press the down arrow key.
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/14c5a367-be7f-4bed-93a3-b370f78f9b30)

**Comment by angelozerr** [comment]
Have you the same problem with LSP JetBrains support?

**Comment by angelozerr** [comment]
I think the second completion item comes from IJ himself (it shows some tokens coming from the editor content)

**Comment by CppCXY** [comment]
Indeed, JetBrains LSP does not have highlighting, including systems using PSI, they do not have default highlighting. However, when I write C# programs with Rider, it does have default highlighting.
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/24c05ca9-0eea-4654-aaa7-8d714d6f2ea9)

**Comment by fbricon** [comment]
JetBrains standard completion, Java or even Python in PyCharm doesn't highlight the 1st item in dark blue, arrow down does that blue highlighting, which is consistent with LSP4IJ:
<img width="594" alt="Screenshot 2024-06-19 at 10 46 22" src="https://github.com/redhat-developer/lsp4ij/assets/148698/2be83742-7bf8-4597-b265-7f6a0c4566fa">
<img width="582" alt="Screenshot 2024-06-19 at 10 46 32" src="https://github.com/redhat-developer/lsp4ij/assets/148698/6f0aee29-fe6c-42d9-a87e-68db594cca22">

**Comment by CppCXY** [comment]
I investigated other IDEs, and indeed, this seems to be the standard behavior of JetBrains IDEs.
