### ISSUE TITLE
Support file link in hover

### ISSUE THREAD

**Issue by CppCXY** [redhat-developer/lsp4ij#376]
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/482a2bb6-142b-4118-801e-bc8d6d987267)
When I press x trying to jump, a vscode pops up:
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/a7568e85-9ec9-4e29-8ffa-68971af3578d)
I hope that IDEA can jump on its own.

**Comment by CppCXY** [comment]
In VSCode, the supported URI format is "{uri}#{line}:{col}-{line}:{col}", I hope IDEA can also support this.

**Comment by angelozerr** [comment]
Could you please share your lsp trace hover.

**Comment by CppCXY** [comment]
> Could you please share your lsp trace hover.

[Trace - 17:22:27] Received response 'textDocument/hover - (45)' in 9ms.
Result: {
  "contents": {
    "kind": "markdown",
    "value": "```lua\nlocal t : ambiguous\n```\n\n___\n[x](file:///C:/Users/zc/Desktop/learn/test2.lua)"
  }
}

**Comment by angelozerr** [comment]
@CppCXY when you write your issue could you please add it the content of your file too.

It will avoid for me to rewriting your sample file by seeing your screenshot. Thanks!

**Comment by CppCXY** [comment]
> @CppCXY when you write your issue could you please add it the content of your file too.
> 
> It will avoid for me to rewriting your sample file by seeing your screenshot. Thanks!

ok, the file:
[learn.zip](https://github.com/user-attachments/files/15911711/learn.zip)

**Comment by angelozerr** [comment]
> In VSCode, the supported URI format is "{uri}#{line}:{col}-{line}:{col}", I hope IDEA can also support this.

You mean that you can write this syntax in your comment?

**Comment by angelozerr** [comment]
> > Could you please share your lsp trace hover.
> 
> ```log
> [Trace - 17:22:27] Received response 'textDocument/hover - (45)' in 9ms.
> Result: {
>   "contents": {
>     "kind": "markdown",
>     "value": "```lua\nlocal t : ambiguous\n```\n\n___\n[x](file:///C:/Users/zc/Desktop/learn/test2.lua)"
>   }
> }
> ```
> 

Thanks!

**Comment by angelozerr** [comment]
> > @CppCXY when you write your issue could you please add it the content of your file too.
> > It will avoid for me to rewriting your sample file by seeing your screenshot. Thanks!
> 
> ok, the file: [learn.zip](https://github.com/user-attachments/files/15911711/learn.zip)

Sorry I wanted to say to add your content file in the issue like:

```lua


--- [x](file:///C:/Users/zc/Desktop/learn/test.lua)
local t

```

**Comment by CppCXY** [comment]
> > > @CppCXY when you write your issue could you please add it the content of your file too.
> > > It will avoid for me to rewriting your sample file by seeing your screenshot. Thanks!
> > 
> > 
> > ok, the file: [learn.zip](https://github.com/user-attachments/files/15911711/learn.zip)
> 
> Sorry I wanted to say to add your content file in the issue like:
> 
> ```lua
> --- [x](file:///C:/Users/zc/Desktop/learn/test.lua)
> local t
> ```

This file uri is pointing to the file itself.

**Comment by CppCXY** [comment]
> In VSCode, the supported URI format is "{uri}#{line}:{col}-{line}:{col}", I hope IDEA can also support this.

I'm sorry, I was wrong, VSCode only supports {uri}#line.

**Comment by angelozerr** [comment]
> ```lua
> --- [x](file:///C:/Users/zc/Desktop/learn/test.lua)
> local t
> ```

So you can write this lua file content:

```lua

--- [x](file:///C:/Users/zc/Desktop/learn/test.lua#10)
local t
```

Is that?

**Comment by CppCXY** [comment]
> > ```lua
> > --- [x](file:///C:/Users/zc/Desktop/learn/test.lua)
> > local t
> > ```
> 
> So you can write this lua file content:
> 
> ```lua
> --- [x](file:///C:/Users/zc/Desktop/learn/test.lua#10)
> local t
> ```
> 
> Is that?

yes

**Comment by angelozerr** [comment]
Ok and could you write relative path?

**Comment by CppCXY** [comment]
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/ffbb7294-bb28-4e5c-be4b-c9390222fa25)
We use this feature to implement Go to types in hover

**Comment by angelozerr** [comment]
@CppCXY I have played in vscode with uri

`[x](file:///C:/Users/zc/Desktop/learn/test.lua#10)`

is working

`[x](file:///C:/Users/zc/Desktop/learn/test.lua#10:5)`

doen't work (it doesnt' jump to 5 clumnà)

**Comment by CppCXY** [comment]
> `[x](file:///C:/Users/zc/Desktop/learn/test.lua#10:5)`
> 
> doen't work (it doesnt' jump to 5 clumnà)

Indeed, it does not support column.

**Comment by angelozerr** [comment]
@CppCXY @FalsePattern the PR about supporting file link in markdown has been merged.

You can install https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-the-ci-builds to test this feature.

Please play with this feature and give us feedback, thanks!

**Comment by angelozerr** [comment]
> > @CppCXY when you write your issue could you please add it the content of your file too.
> > 
> > It will avoid for me to rewriting your sample file by seeing your screenshot. Thanks!
> 
> ok, the file:
> [learn.zip](https://github.com/user-attachments/files/15911711/learn.zip)
> 
    @CppCXY have you tried this feature ? Is it working for your all usecases?

**Comment by CppCXY** [comment]
> @CppCXY have you tried this feature ? Is it working for your all usecases?

I've tried it and found that the format is #L{line}:{col}. In fact, VSCode supports both #{line} and #L{line}, but I've decided to switch to the version you support.

**Comment by angelozerr** [comment]
> I've tried it and found that the format is #L{line}:{col}

I support the both syntax:

 * `#L{line}`
 * `#L{line}:{col}`

**Comment by angelozerr** [comment]
Could you create please an issue to support too `#{line} ` syntax
