### ISSUE TITLE
If formatting is provided through PSI, then LSP's formatting cannot be invoked.

### ISSUE THREAD

**Issue by CppCXY** [redhat-developer/lsp4ij#388]
If intellij-emmylua is installed and sumneko lua is configured through LSP4IJ, then LSP4IJ will not send formatting requests.

**Comment by angelozerr** [comment]
Indeed I did this choice because I was fear to break something if an IJ plugin provide a formatter.

My feeling was if IJ plugin provides a formatter it means that formatter is better than the language server.

I dont know if it is possible to choose a formatter if there are several formatter for a given file.

Do you know that @CppCXY ?

**Comment by CppCXY** [comment]
see my another [plugin](https://github.com/CppCXY/Intellij-EmmyLuaCodeStyle), This plugin operates as a plugin for the IntelliJ-EmmyLua plugin. It is based on the formatter registered through the external tool, and IntelliJ will select it as the highest priority formatter.

**Comment by fbricon** [comment]
Seems like Jetbrains LSP API allows servers to override the IDE-provided formatting: https://github.com/vitallium/intellij-plugin-ruby-lsp/blob/c133940a5b91034076aa90771f46b026db997028/src/main/kotlin/com/github/vitallium/rubylsp/RubyLspServerDescriptor.kt#L45

**Comment by angelozerr** [comment]
It will covered in 0.7.0 with the current PR https://github.com/redhat-developer/lsp4ij/pull/543

**Comment by angelozerr** [comment]
@CppCXY @FalsePattern @themartdev please try  [installing nightly-builds](https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-nightly-builds), read doc at https://github.com/redhat-developer/lsp4ij/blob/main/docs/LSPApi.md#lsp-formatting-feature

For more information ,see https://github.com/redhat-developer/lsp4ij/discussions/561
