### ISSUE TITLE
On MacOS, Server templates are missing unless LSP4IJ is run in dev mode

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/lsp4ij#393]
See:

<img width="637" alt="Screenshot 2024-06-30 at 19 24 06" src="https://github.com/redhat-developer/lsp4ij/assets/148698/3ab72386-0f38-41a1-a9ac-d4af67c341ef">

Templates are only showing up when LSP4IJ is started from source with `./gradlew runIde`

**Comment by angelozerr** [comment]
Thats strange, I have installed LSP4IJ on Windows OS and it works?

**Comment by fbricon** [comment]
Also works on Linux, so seems like a MacOS specific issue. WTAF?!

**Comment by angelozerr** [comment]
I have merged your PR and rebuild a nighthy build that I have installed and it works prefectly on Windows OS.
