### ISSUE TITLE
Semantic highlighting consume a lot of CPU

### ISSUE THREAD

**Issue by CppCXY** [redhat-developer/lsp4ij#394]
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/f5f23fb4-2ec5-4f3c-934f-fb545b4f674a)
Does semantic highlighting consume a lot of CPU? I see it trying to refresh once every second.

After I turn it off, the CPU drops to 7%, but that's still a lot.
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/41fa3898-0c7f-4f03-9f6c-f2953d2f151f)

**Comment by CppCXY** [comment]
[1k_row_code.zip](https://github.com/user-attachments/files/16052174/1k_row_code.zip)
here the test script

**Comment by angelozerr** [comment]
Thanks for reporting your issue. Your CPU problem comes from too when yiu close inspector?

**Comment by CppCXY** [comment]
> Thanks for reporting your issue. Your CPU problem comes from too when yiu close inspector?

When I close inspector: the cpu keep 40%:
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/03c4fc1a-27aa-4b89-8f6a-059a2d1e23f9)

**Comment by angelozerr** [comment]
It is so bad -( Let me investiate your problem.

But is semantic tokens is working for you?

**Comment by CppCXY** [comment]
> But is semantic tokens is working for you?

It's working fine!

**Comment by angelozerr** [comment]
@CppCXY could you re-install nighly build and test again.

If you have again CPU problem, please re-open the issue.

**Comment by angelozerr** [comment]
> @CppCXY could you re-install nighly build and test again.
> 
> If you have again CPU problem, please re-open the issue.

@CppCXY is it working better?

**Comment by CppCXY** [comment]
> @CppCXY is it working better?

No performance issues have been found for the time being.

**Comment by angelozerr** [comment]
> > @CppCXY is it working better?
> 
> No performance issues have been found for the time being.

Thats great
