### ISSUE TITLE
Support semantic token MultilineTokenSupport

### ISSUE THREAD

**Issue by CppCXY** [redhat-developer/lsp4ij#401]
> If multiline tokens are not supported and a tokens length takes it past the end of the line, it should be treated as if the token ends at the end of the line and will not wrap onto the next line.

If the length of a token exceeds the end of this line, it should not continue to the next line.

**Comment by angelozerr** [comment]
Have you a usecase?

**Comment by CppCXY** [comment]
test script here:
[test2.zip](https://github.com/user-attachments/files/16062191/test2.zip)

If the language server detects that the client does not support multiline tokens, it will return multiple single-line tokens, each with a length of 9999. According to LSP, overly long tokens should not continue to the next line. However, LSP4IJ continues them to the following lines, causing the string color to change.

the response:
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/3a623718-bee6-4a10-8fd9-216e498b25af)

**Comment by angelozerr** [comment]
Could you share please your LSP traces, because I would like to start writting tests for sem1ntic tokens by using real LSP traces. I need your full trace with initialize which return legend and semanticTokens/full

**Comment by CppCXY** [comment]
[LSPIJ.zip](https://github.com/user-attachments/files/16063065/LSPIJ.zip)

**Comment by angelozerr** [comment]
@CppCXY have you some cloration, or is semantic fails with a stack trace error?

**Comment by CppCXY** [comment]
> @CppCXY do you have some coloration, or does semantic fail with a stack trace error?

no stack trace,

**Comment by angelozerr** [comment]
Are you sure that your semanticFull trace is for the content of your file that you have attached?

Could you add a screenshot with the result of the problem please.

**Comment by CppCXY** [comment]
"hello" was rendered in gray:
![image](https://github.com/redhat-developer/lsp4ij/assets/40318218/c74e8cfd-a62a-4e10-b795-a25c22a7a0f5)

**Comment by CppCXY** [comment]
This is because Luals splits tokens that span multiple lines into several single-line tokens and sets the token length to 9999, which is in accordance with the language server specifications.
