### ISSUE TITLE
publishDiagnostics does not work

### ISSUE THREAD

**Issue by deanmaster** [redhat-developer/lsp4ij#419]
Hello team,

Currently i'm testing publishDiagnostics in the plugin via nightly build. The reason which I would like to use semantictoken highlight feature.

But unfortunately the semantictoken is working but the textDocument/publishDiagnostics does not work. The json does not show any error which return from server

<img width="819" alt="Screenshot 2024-07-15 at 05 52 05" src="https://github.com/user-attachments/assets/f5698864-6b4c-4968-a5c5-dfe0a8830ba1">

When I use VSCode

<img width="843" alt="Screenshot 2024-07-15 at 05 52 25" src="https://github.com/user-attachments/assets/dabdf22c-0103-4702-ad14-87946c345a9e">

**Comment by angelozerr** [comment]
> But unfortunately the semantictoken is working but the textDocument/publishDiagnostics does not work.

Is publishDiagnostics working with LSP4IJ 0.2.0?

Could you share your LSP trace please. Do you see some textDocument/publishDiagnostics in your trace? If no perhaps, your server expects some settings to enable it?

**Comment by angelozerr** [comment]
Which language server are you trying? Could you give us a link how to download / install in order to we try it.

**Comment by deanmaster** [comment]
hello @angelozerr 

Yes diagnostic is working with 0.2.0

I used JSON Language server from Microsoft plus our custom logic when reading the content of JSON. The stack trace looks like this. For me, it it's normal stack trace for Diagnostics.

<img width="1378" alt="Screenshot 2024-07-15 at 08 43 18" src="https://github.com/user-attachments/assets/9858af16-a4b6-4095-b801-fec691a309a0">

**Comment by angelozerr** [comment]
We did no change between 0.2.0 abour publish diagnostics. Perhaps semantic tokens overrides IJ error?

**Comment by deanmaster** [comment]
hmm that's a very good point then this becomes hard so far I expected it
should work. I will let you know when I come back to the topic. but it's
strange that semantic token overrides IJ error.

**Comment by angelozerr** [comment]
If your language server could provide a settings to disable semtantic tokens,  you could test that.

**Comment by deanmaster** [comment]
I removed everything and reinstalled 0.0.2 and it does not work either :( sorry. Semantic Token is disabled.

**Comment by angelozerr** [comment]
Could you share your ls please.

**Comment by deanmaster** [comment]
The code is in our company's repository. Which code you would like to see ?
I can excerpt the code and put it here.

**Comment by angelozerr** [comment]
I dont want to see some code just play with your ls to try to reproduce your issue.

I tough it is worked with 0.2.0?

**Comment by deanmaster** [comment]
Yes as I remembered it worked in Intelij. I tested our LSP server with
Eclipse,VSCode and Intelij. Probably I mixed up :( i'm sorry. Now when I
disabled everything else the diagnostic does not work obviously in Intelij
Pluging sadly :(

**Comment by deanmaster** [comment]
alright I noticed something. The error is shown in the intellij but quickly
disappears afterward. it does not show permanently.

**Comment by deanmaster** [comment]
As you can see in this image: The error will be disappear after continue working on the json file.

<img width="962" alt="Screenshot 2024-07-15 at 12 49 41" src="https://github.com/user-attachments/assets/9c19464c-7e43-46c1-9231-f86be9e433a2">

**Comment by angelozerr** [comment]
@deanmaster without testing your ls I cannot investigate your problem

**Comment by angelozerr** [comment]
Please share your full lsp trae

**Comment by deanmaster** [comment]
[Untitled.pdf](https://github.com/user-attachments/files/16242776/Untitled.pdf)
I exported the log via PDF file. The behavior is the error is shown in the editor and vanish afterward.

**Comment by angelozerr** [comment]
According your LSP trace the last publish diagnostics is empty, it exlplains why errorr disapear, right?

**Comment by deanmaster** [comment]
I think you noticed correctly, i'm not sure why it happens in this way but the VSCode still shows errors, probably I need to track the server code to see where these 2 notifications come from. Probably LSP Client from VSCode fired something else to trigger validation. But thanks I can close the ticket. I will reopen if I found something else.

**Comment by deanmaster** [comment]
hi @angelozerr I found the bug in validation which build Diagnostics from our language server. The bug is fixed. Thank you, errors are shown correctly lsp4ij

**Comment by angelozerr** [comment]
Nice! I suggest really to use LSP console which helps a lot to understand the behavior of your language server.

**Comment by deanmaster** [comment]
I understood that i have LSP console, what do you mean "use" is that the pdf file which I sent to you or do I need to do something additionally.

**Comment by angelozerr** [comment]
> I understood that i have LSP console, what do you mean "use" is that the pdf file which I sent to you or do I need to do something additionally.

I mean just read lsp traces from lsp console to understand the behavior of your language server like I did.

More lsp console reports the same lsp syntax traces than vscode, so you can easily compare traces between intellij and vscode

**Comment by deanmaster** [comment]
ah thank you yes you're right.
