### ISSUE TITLE
serialization/deserialization for LanguageServer?

### ISSUE THREAD

**Issue by onriv** [redhat-developer/lsp4ij#421]
Hi during the implementation of customized `LanguageServer`, some types and messages return from the lsp server end require some specific serialization/deserialization logic (like deserializing to different subclasses)

Any way to do this? Thanks!

**Comment by CppCXY** [comment]
If you're interested in how to handle messages about the language server, you can refer to my project, although it is implemented in C#. see: https://github.com/CppCXY/LanguageServer.Framework
