### ISSUE TITLE
Feature request: A way for languages or language servers to bypass the canFormat check

### ISSUE THREAD

**Issue by FalsePattern** [redhat-developer/lsp4ij#424]
In AbstractLSPFormattingService, `canFormat` checks for the presence of a LanguageFormatting implementation for a language, and if present, doesn't invoke the LSP formatter.

In the case of ZigBrains, I used both the LSP formatter for manual formatting via ZLS when invoking the formatting action, as well as the intellij autoformatter for correct auto-indentation when creating new lines or code blocks. If the zigbrains `lang.formatter` is removed, auto-indentation breaks, but the ZLS formatter functions.

**Comment by angelozerr** [comment]
Same issue than https://github.com/redhat-developer/lsp4ij/issues/388

**Comment by angelozerr** [comment]
Duplicate of https://github.com/redhat-developer/lsp4ij/issues/388 and covered with the current PR https://github.com/redhat-developer/lsp4ij/pull/543
