### ISSUE TITLE
LSP textDocument/definition doens't open the file when range start / end are equals

### ISSUE THREAD

**Issue by pl0301** [redhat-developer/lsp4ij#430]
I integrated my language server (implemented in Java) into the plugin according to the Developer guide. When I initiated textDocument/definition, I saw the correct response in the console, but IDEA indicated that the definition location could not be found. This is very confusing to me.
![20240724204525](https://github.com/user-attachments/assets/ad7ab1f7-7ad4-4199-82aa-5b1727eb385d)

**Comment by angelozerr** [comment]
Are you sure that your uri is correct?

Is your ls working with vscode?

Could you share your ls and give us some instruction how to start it in ordre to we play  with your ls.

**Comment by pl0301** [comment]
> Are you sure that your uri is correct?
> 
> Is your ls working with vscode?
> 
> Is other feature like completion is working?
> 
> Could you share your ls and give us some instruction how to start it in ordre to we play with your ls.

1,the uri is correct,I can click 

> Are you sure that your uri is correct?
> 
> Is your ls working with vscode?
> 
> Is other feature like completion is working?
> 
> Could you share your ls and give us some instruction how to start it in ordre to we play with your ls.

1. The URI is correct; I can click on the URI to navigate to the corresponding file.

2. Definition jumping is working correctly in VS Code.

3. The completion feature is currently under development and hasn’t been implemented yet, but the definition jumping works correctly in VS Code.

4. I'm sorry, but I cannot provide the language server. The LS is implemented in Java and integrated into the plugin as a JAR package. The startup code is as follows:
![21](https://github.com/user-attachments/assets/11b46488-0e12-457e-b2fe-5b33a3ad839c)
If you need any additional information, please let me know.

**Comment by pl0301** [comment]
this is the plugin.xml
`extensions defaultExtensionNs="com.redhat.devtools.lsp4ij">
        <server id="CSServer"
                name="CS Server"
                factoryClass="cs.plugin.lsp.CSServerFactory">
            <description> </description>
        </server>
        <languageMapping language="CS"
                         serverId="CSServer"/>
    </extensions>`

**Comment by angelozerr** [comment]
> this is the plugin.xml
> `extensions defaultExtensionNs="com.redhat.devtools.lsp4ij">
>         <server id="CSServer"
>                 name="CS Server"
>                 factoryClass="cs.plugin.lsp.CSServerFactory">
>             <description> </description>
>         </server>
>         <languageMapping language="CS"
>                          serverId="CSServer"/>
>     </extensions>`

Every things seems good. I cannot help you more if I cannot test your ls.

Definition works with a lot of ls so I m surprised that it doesnt work for you.

**Comment by fbricon** [comment]
What does the target uri returned by the server look like? Standard file uri? Does it contain special characters? Is the target file in the current project?

**Comment by fbricon** [comment]
Can you provide a screenshot of the error message, so we can determine who's displaying it, IDEA or lsp4ij

**Comment by pl0301** [comment]
> Can you provide a screenshot of the error message, so we can determine who's displaying it, IDEA or lsp4ij

1, the uri just like"file:///Users/pl/Desktop/test2/CS_pop_2024-05-26-master-73e9af0abfe2fa88/2.cs"
2,the target file in the current project
3, If I use the LSP API provided by IDEA（https://plugins.jetbrains.com/docs/intellij/language-server-protocol.html）, the 'go to definition' feature works, so I'm curious if I overlooked something during the integration with LSP4IJ. Are there any more detailed integration guides available, besides the Developer guide guide?
4,this is the lsp console and idea console log, all seem to be normal
![3](https://github.com/user-attachments/assets/eeb4db61-286e-40ec-bb23-2e0f22f73fd2)

![4](https://github.com/user-attachments/assets/c1995617-1208-4631-879e-b015e9623517)
![5](https://github.com/user-attachments/assets/d48c38e1-dff6-4e01-bdf7-bea7312cd649)

**Comment by pl0301** [comment]
I want to see more information, but my log is empty.
![6](https://github.com/user-attachments/assets/f937b656-5de0-4673-a3f9-4596b7b70dc0)

**Comment by pl0301** [comment]
Perhaps you could tell me if there are other LSP4IJ plugins that also run the language server  by executing a local JAR file.

**Comment by angelozerr** [comment]
> Perhaps you could tell me if there are other LSP4IJ plugins that also run the language server  by executing a local JAR file.
> 
> 

If it works with lsp from jetbrains it means that we have a bug.

Could you test your ls with a simple project directory like foo to have an uri like file///Users/pl/Desktop/test2/foo/2.cs"

**Comment by angelozerr** [comment]
> Perhaps you could tell me if there are other LSP4IJ plugins that also run the language server  by executing a local JAR file.
> 
> 

We did that with our intellij quarkus but it seems that LSP4IJ have a bug since lsp from jetbrains is working.

**Comment by angelozerr** [comment]
> I want to see more information, but my log is empty.
> ![6](https://github.com/user-attachments/assets/f937b656-5de0-4673-a3f9-4596b7b70dc0)
> 

This log tab is filled if your ls reports some lsp window/logMessage

**Comment by pl0301** [comment]
> > I want to see more information, but my log is empty.
> > ![6](https://private-user-images.githubusercontent.com/176492779/351908792-f937b656-5de0-4673-a3f9-4596b7b70dc0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODYwOTAsIm5iZiI6MTcyMTg4NTc5MCwicGF0aCI6Ii8xNzY0OTI3NzkvMzUxOTA4NzkyLWY5MzdiNjU2LTVkZTAtNDY3My1hM2Y5LTQ1OTZiN2I3MGRjMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNTM2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTY5YmFhY2ZhNjFlYTIzZDJhZWI1MjY4M2ZhZWM5NTdlNDkxMTkyNDVjMjNlODBmNzkxYmExZDYwOGZhZmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DaqmjVE_s5YhJl1zN1s-BR6lJkYoYNjf3X8VHeBHsPU)
> 
> This log tab is filled if your ls reports some lsp window/logMessage

I wrote the ls log to a temporary file, and from the log, the server appears to be running normally.

**Comment by angelozerr** [comment]
> > > I want to see more information, but my log is empty.
> > > ![6](https://private-user-images.githubusercontent.com/176492779/351908792-f937b656-5de0-4673-a3f9-4596b7b70dc0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODYwOTAsIm5iZiI6MTcyMTg4NTc5MCwicGF0aCI6Ii8xNzY0OTI3NzkvMzUxOTA4NzkyLWY5MzdiNjU2LTVkZTAtNDY3My1hM2Y5LTQ1OTZiN2I3MGRjMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNTM2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTY5YmFhY2ZhNjFlYTIzZDJhZWI1MjY4M2ZhZWM5NTdlNDkxMTkyNDVjMjNlODBmNzkxYmExZDYwOGZhZmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DaqmjVE_s5YhJl1zN1s-BR6lJkYoYNjf3X8VHeBHsPU)
> > 
> > This log tab is filled if your ls reports some lsp window/logMessage
> 
> I wrote the ls log to a temporary file, and from the log, the server appears to be running normally.
> 
> 

OK please try to use a simple folder name.

**Comment by pl0301** [comment]
> > Perhaps you could tell me if there are other LSP4IJ plugins that also run the language server  by executing a local JAR file.
> 
> We did that with our intellij quarkus but it seems that LSP4IJ have a bug since lsp from jetbrains is working.



> > Perhaps you could tell me if there are other LSP4IJ plugins that also run the language server  by executing a local JAR file.
> 
> We did that with our intellij quarkus but it seems that LSP4IJ have a bug since lsp from jetbrains is working.

I don't quite understand. Is it caused by JetBrains? I tried using a simple file, and the result was the same. The trace information was normal, but IDEA indicated that it couldn't be found.  
![678](https://github.com/user-attachments/assets/4d22b01e-4119-4944-8f55-9e96636e92b6)

**Comment by fbricon** [comment]
Can you show intellij's error message?

**Comment by pl0301** [comment]
> Can you show intellij's error message?

this is the idea.log
[idea.log](https://github.com/user-attachments/files/16371193/idea.log)
this is the idea debug console
![4545](https://github.com/user-attachments/assets/7dc0c3a0-6772-4076-b759-7445ea371677)

**Comment by pl0301** [comment]
as you can see,I haven't implemented the completion feature. However, the definition works both in VSCode and in IntelliJ IDEA.

**Comment by pl0301** [comment]
I attempted to use smithy ls for definition, and it worked fine. I noticed that the URI returned by the server is not a standard URI. Could this be the reason?
![smi](https://github.com/user-attachments/assets/f422303b-ea81-4ece-ac75-629f3fc2342d)

**Comment by angelozerr** [comment]
> I attempted to use smithy ls for definition, and it worked fine. I noticed that the URI returned by the server is not a standard URI. Could this be the reason?

No, we use several langugage servers which generate the same uri than you with file:///

> ![smi](https://github.com/user-attachments/assets/f422303b-ea81-4ece-ac75-629f3fc2342d)
>

**Comment by angelozerr** [comment]
> > Can you show intellij's error message?
> 
> this is the idea.log
> [idea.log](https://github.com/user-attachments/files/16371205/idea.log)
> 
> this is the idea debug console
> ![4545](https://github.com/user-attachments/assets/7dc0c3a0-6772-4076-b759-7445ea371677)
> 

There is an error with completion which is not supported. I think your ls send the wrong completion capability

**Comment by angelozerr** [comment]
> > I attempted to use smithy ls for definition, and it worked fine. I noticed that the URI returned by the server is not a standard URI. Could this be the reason?
> 
> No, we use several langugage servers which generate the same uri than you with file:///
> 
> > ![smi](https://github.com/user-attachments/assets/f422303b-ea81-4ece-ac75-629f3fc2342d)
> > 
> 
> 

But please try to update your ls to check if it fixes your problem, but we need to do something on LSP4IJ side

**Comment by pl0301** [comment]
i update my ls,and it seems not work,i still can not go to definition.
![7777](https://github.com/user-attachments/assets/3f9eccd3-3d70-4814-ad3f-64ee184a34cb)

**Comment by angelozerr** [comment]
I have no idea why you have this problem.

We need to debug lsp4ij https://github.com/redhat-developer/lsp4ij/blob/main/src%2Fmain%2Fjava%2Fcom%2Fredhat%2Fdevtools%2Flsp4ij%2Ffeatures%2Fnavigation%2FLSPGotoDeclarationHandler.java#L45 but without your ls I cannot debug it

**Comment by pl0301** [comment]
> I have no idea why you have this problem.
> 
> We need to debug lsp4ij https://github.com/redhat-developer/lsp4ij/blob/main/src%2Fmain%2Fjava%2Fcom%2Fredhat%2Fdevtools%2Flsp4ij%2Ffeatures%2Fnavigation%2FLSPGotoDeclarationHandler.java#L45 but without your ls I cannot debug it

I apologize for not being able to provide you with the ls. I would greatly appreciate it if you could guide me on how to debug

**Comment by fbricon** [comment]
The console log shows an issue with completion. Can you screenshot the error message displayed during the navigation error?

**Comment by angelozerr** [comment]
> The console log shows an issue with completion. Can you screenshot the error message displayed during the navigation error?

Please copy paste your lsp trace in this issue

**Comment by pl0301** [comment]
> The console log shows an issue with completion. Can you screenshot the error message displayed during the navigation error?
When I triggered the definition, there was no error message. The debug log is shown in the picture.
![image](https://github.com/user-attachments/assets/052d85ce-fbb5-4e45-a7d4-e5b98436a5ae)
![image](https://github.com/user-attachments/assets/bf8b2396-4269-4035-ac7a-de5db32d17b9)

**Comment by pl0301** [comment]
> > The console log shows an issue with completion. Can you screenshot the error message displayed during the navigation error?
> 
> Please copy paste your lsp trace in this issue

 Do you mean the console trace of LSP4IJ?
`[Trace - 17:15:12] Sending request 'initialize - (1)'.
Params: {
  "processId": 8596,
  "rootPath": "/Users/pl/Desktop/test",
  "rootUri": "file:///Users/pl/Desktop/test",
  "capabilities": {
    "workspace": {
      "applyEdit": true,
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "delete",
          "rename"
        ]
      },
      "didChangeConfiguration": {
        "dynamicRegistration": true
      },
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "executeCommand": {
        "dynamicRegistration": true
      },
      "workspaceFolders": true,
      "configuration": true,
      "semanticTokens": {
        "refreshSupport": true
      },
      "fileOperations": {
        "didRename": true,
        "willRename": true,
        "dynamicRegistration": true
      },
      "inlayHint": {
        "refreshSupport": true
      }
    },
    "textDocument": {
      "synchronization": {
        "willSave": true,
        "willSaveWaitUntil": true,
        "didSave": true
      },
      "completion": {
        "completionItem": {
          "snippetSupport": true,
          "documentationFormat": [
            "markdown",
            "plaintext"
          ],
          "deprecatedSupport": true,
          "resolveSupport": {
            "properties": [
              "documentation",
              "detail",
              "additionalTextEdits"
            ]
          },
          "insertTextModeSupport": {
            "valueSet": [
              1,
              2
            ]
          },
          "labelDetailsSupport": true
        },
        "completionList": {
          "itemDefaults": [
            "editRange"
          ]
        }
      },
      "hover": {
        "contentFormat": [
          "markdown",
          "plaintext"
        ]
      },
      "signatureHelp": {
        "signatureInformation": {
          "parameterInformation": {
            "labelOffsetSupport": true
          }
        }
      },
      "references": {},
      "documentHighlight": {},
      "formatting": {
        "dynamicRegistration": true
      },
      "rangeFormatting": {
        "dynamicRegistration": true
      },
      "declaration": {
        "linkSupport": true
      },
      "definition": {
        "linkSupport": true
      },
      "typeDefinition": {
        "linkSupport": true
      },
      "implementation": {
        "linkSupport": true
      },
      "codeAction": {
        "codeActionLiteralSupport": {
          "codeActionKind": {
            "valueSet": [
              "quickfix",
              "refactor",
              "refactor.extract",
              "refactor.inline",
              "refactor.rewrite",
              "source",
              "source.organizeImports"
            ]
          }
        },
        "dataSupport": true,
        "resolveSupport": {
          "properties": [
            "edit"
          ]
        },
        "dynamicRegistration": true
      },
      "codeLens": {},
      "documentLink": {},
      "colorProvider": {},
      "rename": {
        "prepareSupport": true
      },
      "publishDiagnostics": {
        "relatedInformation": true,
        "tagSupport": {
          "valueSet": [
            1,
            2
          ]
        },
        "codeDescriptionSupport": true,
        "dataSupport": true
      },
      "foldingRange": {},
      "semanticTokens": {
        "requests": {
          "range": false,
          "full": true
        },
        "tokenTypes": [
          "namespace",
          "type",
          "class",
          "enum",
          "interface",
          "struct",
          "typeParameter",
          "parameter",
          "variable",
          "property",
          "enumMember",
          "event",
          "function",
          "method",
          "macro",
          "keyword",
          "modifier",
          "comment",
          "string",
          "number",
          "regexp",
          "operator",
          "decorator",
          "label"
        ],
        "tokenModifiers": [
          "declaration",
          "definition",
          "readonly",
          "static"
        ],
        "formats": [
          "relative"
        ],
        "multilineTokenSupport": true,
        "serverCancelSupport": true
      },
      "inlayHint": {}
    },
    "window": {
      "workDoneProgress": true,
      "showMessage": {},
      "showDocument": {
        "support": true
      }
    }
  },
  "clientInfo": {
    "name": "IntelliJ",
    "version": "IntelliJ IDEA (build IU-241.18034.62)"
  },
  "trace": "off",
  "workspaceFolders": [
    {
      "uri": "file:///Users/pl/Desktop/test",
      "name": "test"
    }
  ]
}


[Trace - 17:15:13] Received notification 'window/showMessage'
Params: {
  "type": 3,
  "message": "Hello from cloudspec-language-server !"
}


[Trace - 17:15:14] Sending notification 'initialized'
Params: {}


[Trace - 17:15:14] Received response 'initialize - (1)' in 1648ms.
Result: {
  "capabilities": {
    "textDocumentSync": 1,
    "definitionProvider": true,
    "referencesProvider": true,
    "codeActionProvider": false,
    "declarationProvider": true,
    "workspace": {
      "fileOperations": {
        "didCreate": {
          "filters": [
            {
              "pattern": {
                "glob": "**/*.cspec"
              }
            }
          ]
        },
        "didRename": {
          "filters": [
            {
              "pattern": {
                "glob": "**/*.cspec"
              }
            }
          ]
        },
        "willRename": {
          "filters": [
            {
              "pattern": {
                "glob": "**/*.cspec"
              }
            }
          ]
        },
        "didDelete": {
          "filters": [
            {
              "pattern": {
                "glob": "**/*.cspec"
              }
            }
          ]
        }
      }
    }
  }
}


[Trace - 17:15:14] Sending notification 'textDocument/didOpen'
Params: {
  "textDocument": {
    "uri": "file:///Users/pl/Desktop/test/main.cspec",
    "languageId": "cspec",
    "version": 1,
    "text": "$version: 1\nnamespace: a.b\nimport \"./2.cspec\"\nimport \"./33.cspec\"\n\n\n@actionTrail({\n    enable: true\n    `namespace`: \"A\"\n    `name`: \"Aname\"\n})\noperation A {\n    input: AInput\n    output: AOutput\n}\n\n\nresource TestInstance {\n  identifyDefinition: {\n    id: string\n  }\n  properties: {\n    name: test\n  }\n}\n\n"
  }
}


[Trace - 17:15:14] Sending notification 'textDocument/didOpen'
Params: {
  "textDocument": {
    "uri": "file:///Users/pl/Desktop/test/2.cspec",
    "languageId": "cspec",
    "version": 1,
    "text": "$version: 1\nnamespace: a.b\n\nstruct AOutput {\n    a: int32\n}\n\nstruct test{\n    bb:test3\n}\n\nstruct test3{\n    d:my\n}\n@for(TestInstance)\nstruct AInput {\n    $id\n    $name\n}\n"
  }
}


[Trace - 17:15:26] Sending request 'textDocument/definition - (2)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/pl/Desktop/test/main.cspec"
  },
  "position": {
    "line": 12,
    "character": 14
  }
}


[Trace - 17:15:26] Received response 'textDocument/definition - (2)' in 22ms.
Result: [
  {
    "uri": "file:///Users/pl/Desktop/test/2.cspec",
    "range": {
      "start": {
        "line": 15,
        "character": 7
      },
      "end": {
        "line": 15,
        "character": 7
      }
    }
  }
]


`

**Comment by angelozerr** [comment]
> > > The console log shows an issue with completion. Can you screenshot the error message displayed during the navigation error?
> > 
> > Please copy paste your lsp trace in this issue
> 
>  Do you mean the console trace of LSP4IJ?
> 
> ```
> [Trace - 17:15:12] Sending request 'initialize - (1)'.
> Params: {
>   "processId": 8596,
>   "rootPath": "/Users/pl/Desktop/test",
>   "rootUri": "file:///Users/pl/Desktop/test",
>   "capabilities": {
>     "workspace": {
>       "applyEdit": true,
>       "workspaceEdit": {
>         "documentChanges": true,
>         "resourceOperations": [
>           "create",
>           "delete",
>           "rename"
>         ]
>       },
>       "didChangeConfiguration": {
>         "dynamicRegistration": true
>       },
>       "didChangeWatchedFiles": {
>         "dynamicRegistration": true
>       },
>       "executeCommand": {
>         "dynamicRegistration": true
>       },
>       "workspaceFolders": true,
>       "configuration": true,
>       "semanticTokens": {
>         "refreshSupport": true
>       },
>       "fileOperations": {
>         "didRename": true,
>         "willRename": true,
>         "dynamicRegistration": true
>       },
>       "inlayHint": {
>         "refreshSupport": true
>       }
>     },
>     "textDocument": {
>       "synchronization": {
>         "willSave": true,
>         "willSaveWaitUntil": true,
>         "didSave": true
>       },
>       "completion": {
>         "completionItem": {
>           "snippetSupport": true,
>           "documentationFormat": [
>             "markdown",
>             "plaintext"
>           ],
>           "deprecatedSupport": true,
>           "resolveSupport": {
>             "properties": [
>               "documentation",
>               "detail",
>               "additionalTextEdits"
>             ]
>           },
>           "insertTextModeSupport": {
>             "valueSet": [
>               1,
>               2
>             ]
>           },
>           "labelDetailsSupport": true
>         },
>         "completionList": {
>           "itemDefaults": [
>             "editRange"
>           ]
>         }
>       },
>       "hover": {
>         "contentFormat": [
>           "markdown",
>           "plaintext"
>         ]
>       },
>       "signatureHelp": {
>         "signatureInformation": {
>           "parameterInformation": {
>             "labelOffsetSupport": true
>           }
>         }
>       },
>       "references": {},
>       "documentHighlight": {},
>       "formatting": {
>         "dynamicRegistration": true
>       },
>       "rangeFormatting": {
>         "dynamicRegistration": true
>       },
>       "declaration": {
>         "linkSupport": true
>       },
>       "definition": {
>         "linkSupport": true
>       },
>       "typeDefinition": {
>         "linkSupport": true
>       },
>       "implementation": {
>         "linkSupport": true
>       },
>       "codeAction": {
>         "codeActionLiteralSupport": {
>           "codeActionKind": {
>             "valueSet": [
>               "quickfix",
>               "refactor",
>               "refactor.extract",
>               "refactor.inline",
>               "refactor.rewrite",
>               "source",
>               "source.organizeImports"
>             ]
>           }
>         },
>         "dataSupport": true,
>         "resolveSupport": {
>           "properties": [
>             "edit"
>           ]
>         },
>         "dynamicRegistration": true
>       },
>       "codeLens": {},
>       "documentLink": {},
>       "colorProvider": {},
>       "rename": {
>         "prepareSupport": true
>       },
>       "publishDiagnostics": {
>         "relatedInformation": true,
>         "tagSupport": {
>           "valueSet": [
>             1,
>             2
>           ]
>         },
>         "codeDescriptionSupport": true,
>         "dataSupport": true
>       },
>       "foldingRange": {},
>       "semanticTokens": {
>         "requests": {
>           "range": false,
>           "full": true
>         },
>         "tokenTypes": [
>           "namespace",
>           "type",
>           "class",
>           "enum",
>           "interface",
>           "struct",
>           "typeParameter",
>           "parameter",
>           "variable",
>           "property",
>           "enumMember",
>           "event",
>           "function",
>           "method",
>           "macro",
>           "keyword",
>           "modifier",
>           "comment",
>           "string",
>           "number",
>           "regexp",
>           "operator",
>           "decorator",
>           "label"
>         ],
>         "tokenModifiers": [
>           "declaration",
>           "definition",
>           "readonly",
>           "static"
>         ],
>         "formats": [
>           "relative"
>         ],
>         "multilineTokenSupport": true,
>         "serverCancelSupport": true
>       },
>       "inlayHint": {}
>     },
>     "window": {
>       "workDoneProgress": true,
>       "showMessage": {},
>       "showDocument": {
>         "support": true
>       }
>     }
>   },
>   "clientInfo": {
>     "name": "IntelliJ",
>     "version": "IntelliJ IDEA (build IU-241.18034.62)"
>   },
>   "trace": "off",
>   "workspaceFolders": [
>     {
>       "uri": "file:///Users/pl/Desktop/test",
>       "name": "test"
>     }
>   ]
> }
> 
> 
> [Trace - 17:15:13] Received notification 'window/showMessage'
> Params: {
>   "type": 3,
>   "message": "Hello from cloudspec-language-server !"
> }
> 
> 
> [Trace - 17:15:14] Sending notification 'initialized'
> Params: {}
> 
> 
> [Trace - 17:15:14] Received response 'initialize - (1)' in 1648ms.
> Result: {
>   "capabilities": {
>     "textDocumentSync": 1,
>     "definitionProvider": true,
>     "referencesProvider": true,
>     "codeActionProvider": false,
>     "declarationProvider": true,
>     "workspace": {
>       "fileOperations": {
>         "didCreate": {
>           "filters": [
>             {
>               "pattern": {
>                 "glob": "**/*.cspec"
>               }
>             }
>           ]
>         },
>         "didRename": {
>           "filters": [
>             {
>               "pattern": {
>                 "glob": "**/*.cspec"
>               }
>             }
>           ]
>         },
>         "willRename": {
>           "filters": [
>             {
>               "pattern": {
>                 "glob": "**/*.cspec"
>               }
>             }
>           ]
>         },
>         "didDelete": {
>           "filters": [
>             {
>               "pattern": {
>                 "glob": "**/*.cspec"
>               }
>             }
>           ]
>         }
>       }
>     }
>   }
> }
> 
> 
> [Trace - 17:15:14] Sending notification 'textDocument/didOpen'
> Params: {
>   "textDocument": {
>     "uri": "file:///Users/pl/Desktop/test/main.cspec",
>     "languageId": "cspec",
>     "version": 1,
>     "text": ""
>   }
> }
> 
> 
> [Trace - 17:15:14] Sending notification 'textDocument/didOpen'
> Params: {
>   "textDocument": {
>     "uri": "file:///Users/pl/Desktop/test/2.cspec",
>     "languageId": "cspec",
>     "version": 1,
>     "text": ""
>   }
> }
> 
> 
> [Trace - 17:15:26] Sending request 'textDocument/definition - (2)'.
> Params: {
>   "textDocument": {
>     "uri": "file:///Users/pl/Desktop/test/main.cspec"
>   },
>   "position": {
>     "line": 12,
>     "character": 14
>   }
> }
> 
> 
> [Trace - 17:15:26] Received response 'textDocument/definition - (2)' in 22ms.
> Result: [
>   {
>     "uri": "file:///Users/pl/Desktop/test/2.cspec",
>     "range": {
>       "start": {
>         "line": 15,
>         "character": 7
>       },
>       "end": {
>         "line": 15,
>         "character": 7
>       }
>     }
>   }
> ]
> 
> ```
>  

Your lsp trace seems correct. I dont understand.

To debug LSP4IJ I am sorry I have no time to explain you how to do that now

**Comment by pl0301** [comment]
I would be more than happy to share it with you, but I need to submit a request to the company first，So please wait a day or two first.

**Comment by angelozerr** [comment]
I will able to test your ls next week if I will find some time.

**Comment by pl0301** [comment]
> I will able to test your ls next week if I will find some time.

thank you very much

**Comment by pl0301** [comment]
Hello, I think I have found the cause. It appears that the issue lies with the doToPsiElement method in the LSPPsiElementFactory interface. My language server returns the same start and end positions for definitions, which causes the textRange in doToPsiElement to be null. As a result, the returned psiElement is an empty array, and IntelliJ can't find it. I resolved this issue by making the server return a position offset by one, but I believe the design of lsp4ij is unreasonable in this respect. The definition result doesn't actually need a complete range,a single position is sufficient. Both VSCode and IntelliJ's native LSP support can run with just the position information.
![12345](https://github.com/user-attachments/assets/5581a03f-228c-437e-938b-6a0fc6c39028)
![67890](https://github.com/user-attachments/assets/6637a664-b1ba-4293-8192-8c5e06420b4f)

**Comment by angelozerr** [comment]
@pl0301 I did a fix,@pl301 could you please install the LSP4IJ zip coming from https://github.com/redhat-developer/lsp4ij/actions/runs/10162519883 and tell me if it fixes your issue.

Thanks.

**Comment by pl0301** [comment]
> @pl0301 I did a fix,@pl301 could you please install the LSP4IJ zip coming from https://github.com/redhat-developer/lsp4ij/actions/runs/10162519883
> 
> ![image](https://private-user-images.githubusercontent.com/1932211/353460919-019f422c-6184-409a-a46a-1315ebeb41d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDM2ODgsIm5iZiI6MTcyMjM0MzM4OCwicGF0aCI6Ii8xOTMyMjExLzM1MzQ2MDkxOS0wMTlmNDIyYy02MTg0LTQwOWEtYTQ2YS0xMzE1ZWJlYjQxZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzBUMTI0MzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjFhMzcyMDIwYTBlODFmNDU1ZTg3Y2Q4YjkxZjdjN2M3NzJhNzk4MGM3MDNjNjFhYjkzNmRkZmJiYWQ5NjQ3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bWIhEgPN360uh10tB6TolQfh2-Jz9xVDDFttGrAtxv0)
> 
> and tell me if it fixes your issue.
> 
> Thanks.

The issue has been fixed. Your work is excellent! It has greatly simplified the development of IDEA custom language plugins.
![730](https://github.com/user-attachments/assets/b23cdfb6-6c62-4204-904e-d9a5fc917714)
![731](https://github.com/user-attachments/assets/0a20e8b6-ea45-44f2-8d86-11e6990fa313)
