### ISSUE TITLE
Fully typed out snippet does not autocomplete

### ISSUE THREAD

**Issue by FalsePattern** [redhat-developer/lsp4ij#435]
Original bug report at https://github.com/FalsePattern/ZigBrains/issues/58, by @AiziChen:

> ## `print` snippet does not auto-complete

> When I type `prin` then press tab/enter key, snippet completion done well. but when I type total characters `print`, it does not doing complete automatically.

> The same as snippet `main` does not work, too.

Upstreamed here, autocomplete is fully handled by LSP4IJ (`LSPCompletionContributor`)

**Comment by angelozerr** [comment]
Could you share your lsp traces please

**Comment by angelozerr** [comment]
> Original bug report at https://github.com/FalsePattern/ZigBrains/issues/58, by @AiziChen:
> 
> > ## `print` snippet does not auto-complete
> 
> > When I type `prin` then press tab/enter key, snippet completion done well. but when I type total characters `print`, it does not doing complete automatically.
> 
> > The same as snippet `main` does not work, too.
> 
> Upstreamed here, autocomplete is fully handled by LSP4IJ (`LSPCompletionContributor`)

Perhaps it is the same issue than https://github.com/redhat-developer/lsp4ij/issues/383 ?

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/lsp4ij/pull/440

**Comment by angelozerr** [comment]
@FalsePattern you can install https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-nightly-builds which should fix your issue.

**Comment by FalsePattern** [comment]
CC @AiziChen

**Comment by AiziChen** [comment]
@angelozerr @FalsePattern  It works gread! Thank you so much!
