### ISSUE TITLE
getting dependency issue

### ISSUE THREAD

**Issue by shishir-11** [redhat-developer/lsp4ij#436]
![image](https://github.com/user-attachments/assets/2a3d3f8c-758b-4b2d-86fb-6c33fc73edb4)
I have tried reinstalling the plugin and adding things to depencies in build.gradle.kts file buut iit still persists . I am trying to build a LSPclient for a project.

**Comment by fbricon** [comment]
try clicking on the synchronize icon on the Gradle view

<img width="451" alt="Screenshot 2024-08-03 at 19 46 11" src="https://github.com/user-attachments/assets/d5f5f0a2-5b9f-42ea-a57f-350a89bacc55">

**Comment by shishir-11** [comment]
it does not change it for me . 
![image](https://github.com/user-attachments/assets/f6cd711a-12de-4d0c-bef4-c99d029c231e)
I've reinstalled this extension too but idk why it does not work.

**Comment by angelozerr** [comment]
@shishir-11 I suggest you see some example of IJ plugin which uses LSP4IJ https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#who-is-using-lsp4ij (IJ Quarkus is little complex, so I suggest to skip it)

**Comment by angelozerr** [comment]
@shishir-11 is your issue is fixed?

**Comment by angelozerr** [comment]
I close the issue, @shishir-11 please reopen it if you have again the problem.
