### ISSUE TITLE
Can't see the signature helper.

### ISSUE THREAD

**Issue by CppCXY** [redhat-developer/lsp4ij#442]
the lsp reponse about signatureHelper:
```json
{
    "signatureHelpProvider": {
      "triggerCharacters": [
        "(",
        ","
      ]
    }
}
```
add parameterInfo to plugin.xml:
```xml
<codeInsight.parameterInfo
        language="Lua"
        implementationClass="com.redhat.devtools.lsp4ij.features.signatureHelp.LSPParameterInfoHandler"/>
```

the project [url](https://github.com/EmmyLua/Intellij-EmmyLua2)

can download the plugin from: https://github.com/EmmyLua/Intellij-EmmyLua2/actions/runs/10316582699

**Comment by CppCXY** [comment]
see:
![debug](https://github.com/user-attachments/assets/a94c7c84-fdf1-460b-9f9f-eb00f4c1adf3)

**Comment by angelozerr** [comment]
If you do Ctr+P inside (), do you see signature help?

**Comment by CppCXY** [comment]
> If you do `Ctr+P` inside (), do you see signature help?

yes, I can see:
![image](https://github.com/user-attachments/assets/a4274d48-afd5-4c41-b19b-5f68858eb66d)

However, it will not update afterwards because my signature can change dynamically.

**Comment by angelozerr** [comment]
Ok it means LSP signature help is working. If you want to process the signature help when you apply completion, you need to select the standard `Show the parameter info popup` option (it works like other language like Java).

![image](https://github.com/user-attachments/assets/4ce956d5-e15c-4cfa-9d30-bfff5ee85ae3)

**Comment by angelozerr** [comment]
> However, it will not update afterwards because my signature can change dynamically.

Sorry I have not understood the problem?

**Comment by CppCXY** [comment]
> Ok it means LSP signature help is working. If you want to process the signature help when you apply completion, you need to select the standard `Show the parameter info popup in ...` option (it works like other language like Java).

 I still can't get the signature unless I press Ctrl+P.
![debug](https://github.com/user-attachments/assets/f1ed7a5a-865b-4cd5-845c-fd2915838168)

**Comment by angelozerr** [comment]
Do you see some LSP trace of signature help when you apply completion?

**Comment by CppCXY** [comment]
> Do you see some LSP trace of signature help when you apply completion?

no, I can't see any signature help protocol

**Comment by angelozerr** [comment]
And if you do ctrl+p?

**Comment by CppCXY** [comment]
When I press ctrl + p, I always get 2 times signatureHelper protocol 
![image](https://github.com/user-attachments/assets/86e9bf7f-396f-4969-8ce9-c46220f0cf86)

**Comment by CppCXY** [comment]
I am certain that while editing the code, IntelliJ did not call the findElementForParameterInfo method, so there is no signature helper, I inherited the LSP class and did not find any calls unless I pressed Ctrl+P.
![image](https://github.com/user-attachments/assets/ed41cb6a-aafb-4ce3-b9d9-d410e5ea2e1f)

**Comment by angelozerr** [comment]
The auto popup is opened here https://github.com/redhat-developer/lsp4ij/blob/16d1c5a654d25d1a4429aa4bfdb89b02cb29c482/src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java#L137 I suggest that you debug LSP4IJ to understand the problem.

**Comment by CppCXY** [comment]
> The auto popup is opened here
> 
> https://github.com/redhat-developer/lsp4ij/blob/16d1c5a654d25d1a4429aa4bfdb89b02cb29c482/src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java#L137
> 
> I suggest that you debug LSP4IJ to understand the problem.

![signature](https://github.com/user-attachments/assets/42a630b5-06c9-4fe0-a826-d861f6811d2a)

donot enter the breakpoint

**Comment by angelozerr** [comment]
If you set a breakpoint in LSPCompletionProposal it should stop when you open completion, right?

If no it means that you cannot debug LSP4IJ

**Comment by CppCXY** [comment]
> If you set a breakpoint in LSPCompletionProposal it should stop when you open completion, right?
> 
> If no it means that you cannot debug LSP4IJ

I can debug in other method 
![image](https://github.com/user-attachments/assets/497d6c72-cf16-45ae-b508-e3474a0f5ed8)

**Comment by CppCXY** [comment]
it can be invoke when this completionItem can execute command:
![image](https://github.com/user-attachments/assets/71320ff7-9d1a-4bf8-b8ea-52b56e63fe40)

**Comment by CppCXY** [comment]
> it can be invoke when this completionItem can execute command

My mistake, it will only be called when selected completion and tab, but cannot be invoked during normal typing.

**Comment by angelozerr** [comment]
Exactly! Is it working when you select completion ? This behavior is the same for other languages like Java, right?

**Comment by CppCXY** [comment]
> Exactly! Is it working when you select completion ? This behavior is the same for other languages like Java, right?

Even when completion is selected, paramInfo still cannot be triggered. I tried customizing an empty paramInfoHandler, but it still couldn't hit the breakpoint during typing. I think this might be related to the PSI system.

**Comment by angelozerr** [comment]
> I think this might be related to the PSI system.

I think so, I suggest that you debug the Jebrains code of the autoPopupParameterInfo.

**Comment by CppCXY** [comment]
I found that it was because LSPTypedHandler returned stop:
![image](https://github.com/user-attachments/assets/dfce8563-8ff6-4f5a-8750-23080be0e0b3)


which caused the subsequent execution to fail.
![image](https://github.com/user-attachments/assets/d57bb961-2fde-41aa-9719-133d02982ff2)

**Comment by CppCXY** [comment]
when I change to continue:
![image](https://github.com/user-attachments/assets/8625b31c-8014-4ec0-967c-8e7e24e997fd)
 it work well:
![image](https://github.com/user-attachments/assets/04681b6c-1536-41de-b26b-7c19d1870a40)

so why is it return stop?
