### ISSUE TITLE
runAsync may throw exception and no log for it

### ISSUE THREAD

**Issue by onriv** [redhat-developer/lsp4ij#448]
Hi it seems https://github.com/redhat-developer/lsp4ij/blob/31e42d6da61cb9126053a70a97bbfba9f4eb5a97/src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java#L260 may throw exceptions (in my case it’s "java.io.IOException: The pipe is being closed") but no error log for it

**Comment by angelozerr** [comment]
@onriv I created the PR 

Once the Build zip Action https://github.com/redhat-developer/lsp4ij/actions/runs/10352858282 is finished, please download it and install it and please tell me if it is working for you.

**Comment by angelozerr** [comment]
@onriv my PR fixes your issue, right?
