### ISSUE TITLE
Unable to show diagnostics when renaming a currently-open file

### ISSUE THREAD

**Issue by bzoracler** [redhat-developer/lsp4ij#454]
I'm trying to get my Language Server to analyse and re-publish diagnostics for a file that has been renamed using PyCharm's `Rename` dialogue (https://www.youtube.com/watch?v=IqPm9RYTNBM&t=32s). However, the diagnostics are not appearing, even though I've confirmed that they are being generated.

Looking at the `Traces`, I see that, upon getting PyCharm to rename the file, the following events are happening:

- ```
  Sending notification 'textDocument/didClose'
  Params: {
    "textDocument": {
      "uri": <URI before renaming>
    }
  }
  ```
- ```
  Sending notification 'workspace/didChangeWatchedFiles'
  Params: {
    "changes": [
      {
        "uri": <URI before renaming>,
        "type": 3
      },
      {
        "uri": <URI after renaming>,
        "type": 1
      }
    ]
  }
- ```
  Received notification 'textDocument/publishDiagnostics'
  Params: {
    "uri": <URI after renaming>,
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 22,
            "character": 8
          },
          "end": {
            "line": 22,
            "character": 9
          }
        },
        "severity": 1,
        "code": <...>,
        "source": <...>,
        "message": <...>
      },
      <...>
    ]
  }
  ```

However, the published diagnostics are not shown in the PyCharm editor.

I suspect the problem is that a `textDocument/didOpen` event on the `<URI after renaming>` is not being received by the server (or even being generated at all). None of the LSP methods seem to be registering changes on the opened file `<URI after renaming>` until after I close this file and re-open it.

Is there something I forgot to do on the server side to make this work? Could it be an OS-specific bug, e.g. with Windows Paths and capitalisation? (I didn't test this on any other OS's except Windows, as I don't have access to any others at the moment).

Environment:
- OS: Windows 11 Home 22631.3958
- PyCharm 2024.1.6, 2024.2
- LSP4IJ version: 0.3.0

---

EDIT: Forgot to mention - I'm using a User-defined language server, not a plugin.

**Comment by angelozerr** [comment]
At first I suggest that you integrate your ls in vscode and study the LSP traces. 

Your LS should support https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didRename to rename a file.

My fear is  that you have not LSP rename but an another rename dialog, and I'm not sure if it will work corretly.

But at first please see the LSP traces that you need to have (with vscode) to try to do the same thing on LSP4IJ side.

**Comment by bzoracler** [comment]
Thanks for the suggestions.

I've registered the methods for the renaming operations, so now PyCharm's `Rename` dialog causes the following Trace:
1. `Sending request 'workspace/willRenameFiles'`
2. `Received response 'workspace/willRenameFiles'`
3. `Sending notification 'textDocument/didClose'`
4. `Sending notification 'workspace/didChangeWatchedFiles'`
5. `Sending notification 'workspace/didRenameFiles'`
6. `Received notification 'textDocument/publishDiagnostics'`

It seems to me that the server is correctly going through the client (PyCharm) for the rename request.

Based on https://github.com/microsoft/vscode-languageserver-node/issues/1186, renaming a file is supposed to additionally trigger `'textDocument/didOpen'`, but this is not happening.

Unlike that issue, I'm not just changing the filename's casing - I'm adding and deleting characters from the file name (`aaaaaa.py` -> `bbbbbb.py`), but I'm not having any luck getting `'textDocument/didOpen'` to trigger.

**Comment by bzoracler** [comment]
I tested the language server in VSCode, which definitely fires a `textDocument/didOpen`:

1. `Sending request 'workspace/willRenameFiles'`
2. `Received response 'workspace/willRenameFiles'`
3. `Sending notification 'textDocument/didClose'`
4. `Sending notification 'textDocument/didOpen'` - Present in VSCode, missing in LSP4IJ
5. `Sending notification 'workspace/didChangeWatchedFiles'`
6. `Sending notification 'workspace/didRenameFiles'`
7. `Received notification 'textDocument/publishDiagnostics'`

---

I had a quick browse through the LSP4IJ repo, and I'm wondering if something's missing at the end here?

https://github.com/redhat-developer/lsp4ij/blob/294dd31a9bff03c914aee63286c9156e5be6c3ca/src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java#L64-L79

From https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didRename (emphasis mine):

> Document renames should be signaled to a server sending a document close notification with the document’s old name **followed by an open notification using the document’s new name**.

**Comment by angelozerr** [comment]
Could you create a PR with your suggestion please?
