### ISSUE TITLE
Question：How to use the latest version

### ISSUE THREAD

**Issue by pl0301** [redhat-developer/lsp4ij#464]
![image](https://github.com/user-attachments/assets/92bcd176-31be-418f-97f8-552122c014de)
I'm integrating lsp4ij, and I noticed that the current version in the plugin marketplace is 0.3.0. However, I can still build successfully with version 0.4.0. How can I obtain the latest version?

**Comment by angelozerr** [comment]
0.4.0 should be available https://plugins.jetbrains.com/plugin/23257-lsp4ij/edit/versions

**Comment by pl0301** [comment]
> 0.4.0 should be available https://plugins.jetbrains.com/plugin/23257-lsp4ij/edit/versions

ok

**Comment by angelozerr** [comment]
@pl0301 can we close this issue?

**Comment by pl0301** [comment]
> @pl0301 can we close this issue?

Sure, go ahead.
