### ISSUE TITLE
Semantic tokens attributes not applied on first start

### ISSUE THREAD

**Issue by harry-xm** [redhat-developer/lsp4ij#475]
When I quit and reopen a project leaving a file open, the underlines on local variables are gone until I reopen the file.

![first open](https://github.com/user-attachments/assets/5d3cd76d-995b-4012-853a-3966d3178502)

![reopen](https://github.com/user-attachments/assets/7dbda0e9-56aa-4ce3-88f2-e307cb23365f)

#### IDE information

```
PyCharm 2024.2.0.1 (Community Edition)
Build #PC-242.20224.428, built on August 21, 2024
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.redhat.devtools.lsp4ij (0.4.0)
```

```
rust-analyzer 1.80.1 (3f5fd8dd 2024-08-06)
```

**Comment by angelozerr** [comment]
Do you see in LSP console https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserGuide.md#lsp-console some sematicTokens LSP traces?

**Comment by angelozerr** [comment]
I wonder how vscode manages this usecase? 

LSP4IJ consumes semanticTokens when editor is opened and when language server is started. rust-analyzer returns an empty semanticTokens when it loads project, but LSP4IJ have no knowledge about loading project.

**Comment by angelozerr** [comment]
> You mean semanticTokens traces? Yes, there were.

It isthe refresh of semanticTokens, but what about 'textDocument/semanticTokens/full ' response:

```
[Trace - 14:57:02] Received response 'textDocument/semanticTokens/full - (7)' in 29ms.
Result: {
  "resultId": "1",
  "data": [
    0,
    0,
    3,
    6,
...
```

I suspect that rust-analyzer returns an empty response when rust-analyzer is starting.

> Besides semantic tokens attributes, syntax highlighting is also affected. See the non-gray vs. gray /// in screenshots from OP.

I cannot reproduce the problem. To check if problem comes from LSP semantic tokens and understand how LSP semantic tokens highlights the editor content, I suggest that you use https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserGuide.md#semantic-tokens-inspector

**Comment by angelozerr** [comment]
> The trace log is too long and got trimmed, but if I terminate the server early:

Are you using LSP console to get trace https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserGuide.md#lsp-console It should be easy to copy/paste trace (you can use Ctrl+F to search some trace.

> the first response I got is this:

And what about last trace of `Received response 'textDocument/semanticTokens/full`. if data is empty it is normal that semantic tokens doesn't work.

Have you a `Received request 'workspace/semanticTokens/refresh ` after a `Received response 'textDocument/semanticTokens/full ` ?

**Comment by angelozerr** [comment]
@harry-xm 

Could you please download the zip from https://github.com/redhat-developer/lsp4ij/actions/runs/10642883658 and install it (see https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-the-ci-builds) and tell me if it fixes your issue.

Thanks!

**Comment by angelozerr** [comment]
> @angelozerr Yes, it fixes the issue. Thanks!

You are welcome! Thanks for having tested the fix. I merged the PR,you can install [nightly-builds](https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-nightly-builds).
