### ISSUE TITLE
Support rendered view of comments

### ISSUE THREAD

**Issue by harry-xm** [redhat-developer/lsp4ij#482]
IntelliJ platform supports rendering Markdown in comments. For example,

![Screenshot of edit view](https://github.com/user-attachments/assets/f63eba70-549f-4c08-939e-8f6415e96c06)

can be rendered into

![Screenshot of rendered view](https://github.com/user-attachments/assets/a9eaab3d-ab00-44a3-b789-9cf93921df7f)

which is the default in reader mode and is used to display library code.

**Comment by angelozerr** [comment]
I'm not sure that it is the goal of LSP. Have you some idea how IntelliJ is managing that?

**Comment by angelozerr** [comment]
> If this is language-specific and not part of the LSP protocol, it is indeed out of scope for LSP4IJ.

I think so. Nothing about that in [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/).

> I'm wondering if LSP4IJ could have its developer guide mention these optional features that need to be implemented in the language plugin.

I suggest that you read https://github.com/redhat-developer/lsp4ij/blob/main/docs/LSPSupport.md where you can see what we support and what we don't support it.

Please close the issue if the doc is enough.

**Comment by angelozerr** [comment]
> I don't think existing docs provide the best guidance possible for plugin authors, but that should be opened as a different issue. 

It provides what LSP4IJ is supporting and not according to the LSP specification. For instance `rendering Markdown in comments` is not a feature supported by LSP and you will see that in the [LSP support](https://github.com/redhat-developer/lsp4ij/blob/main/docs/LSPSupport.md), right?

Main features should work out of the box and if it is not the case, the doc warns that like https://github.com/redhat-developer/lsp4ij/blob/main/docs/LSPSupport.md#signature-help

What do you need more?
