### ISSUE TITLE
Plugin API to hide specific types of Codelens

### ISSUE THREAD

**Issue by harry-xm** [redhat-developer/lsp4ij#484]
An another idea is to provide an API to hide the Codelens with an IJ plugin. Please create an issue for that.

_Originally posted by @angelozerr in https://github.com/redhat-developer/lsp4ij/discussions/479#discussioncomment-10459664_

**Comment by angelozerr** [comment]
This feature is covered by the LSP API PR https://github.com/redhat-developer/lsp4ij/pull/543 please read the doc docs/LSPApi.md (LSP CodeLens feature section)

**Comment by angelozerr** [comment]
See https://github.com/redhat-developer/lsp4ij/blob/main/docs/LSPApi.md#lsp-codeLens-feature
