### ISSUE TITLE
`Edit / Find Usages  / Show Usages` is broken. 

### ISSUE THREAD

**Issue by kristofvb** [redhat-developer/lsp4ij#504]
Hi,

I am using IntelliJ IDEA 2024.2.1 (Ultimate Edition) with Quarkus Tools
  com.redhat.devtools.lsp4ij (0.4.0)
  com.redhat.devtools.intellij.quarkus (2.0.2)

Whenever I try to use Find Usages it turns up with an empty result. Am I missing some other plugins or some setting to make this work?

I have already tried rebuilding the caches to no avail. Disabling the Quarkus Tools plugin resolves the issue.

Thanks for your help.

**Comment by angelozerr** [comment]
> So I am actually talking about the 'Show Usages' functionality. 

Ok I see now! You are right, it doesn't work.

I have tried to do a fix in https://github.com/redhat-developer/lsp4ij/pull/505

Could you please download the zip from https://github.com/redhat-developer/lsp4ij/actions/runs/10691547888 and install it (see https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-the-ci-builds) and tell me if everythinh is working (menus and shortcuts for Find usages, Show Usages, etc)?

**Comment by kristofvb** [comment]
I am afraid it is not yet fixed. I still need to do a FInd Usages first to make the Show Usages work.

**Comment by angelozerr** [comment]
> I am afraid it is not yet fixed. I still need to do a FInd Usages first to make the Show Usages work.

Without my PR, `Show Usages` is not working, right?

**Comment by kristofvb** [comment]
`Show Usages` is **not** working with LSP4IJ 0.4.0 and it is **not** working with your 0.4.1-SNAPSHOT.

**Comment by angelozerr** [comment]
It is an horrible issue. Sometimes it is working and sometimes no.

I need to debug again IntelliJ himself to try to find a fix.

I am sorry for this really annoying bug. 

I will ping you as soon as I will find a solution.

**Comment by angelozerr** [comment]
@kristofvb please retry by installing build zip from https://github.com/redhat-developer/lsp4ij/actions/runs/10702262213

**Comment by kristofvb** [comment]
This SNAPSHOT build seems to fix it.

**Comment by angelozerr** [comment]
Nice! Thanks for having tested the fix.
