### ISSUE TITLE
Feature：DidChange

### ISSUE THREAD

**Issue by pl0301** [redhat-developer/lsp4ij#507]
Hello, I noticed that when performing the git checkout operation, the didChange request is triggered only for the open files and not for others. Is this a bug? If not, could this feature be supported? For example, when I perform a checkout, I would like all changed files in the current workspace to send a didChange notification.

**Comment by angelozerr** [comment]
> Hello, I noticed that when performing the git checkout operation, the didChange request is triggered only for the open files and not for others. Is this a bug? 

I don't think so. When you read https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didChange this notification is send after a didOpen, so it means that file must be opened.

> If not, could this feature be supported? 

As I said you, according to the LSP specification, didChange is sent when file is opened. But to be sure about that,I suggest that you create an issue at https://github.com/microsoft/vscode-languageserver-node/issues to be sure that didChange works only with opened file.

>For example, when I perform a checkout, I would like all changed files in the current workspace to send a didChange notification.

My understand is that you want to track file content changes (opened and closed files). To do that LSP specification provides https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#didChangeWatchedFilesRegistrationOptions, it means that your language server need to regsiter file watchers that LSP4IJ is supporting https://github.com/redhat-developer/lsp4ij/blob/main/docs/LSPSupport.md#workspace-features and in this case you will receive https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWatchedFiles notification.

But please note that you will receive notification about changes of file content but you will not receive the file content (like didChange does).

I suggest you too that you integrate your language server in vscode to check the didChange behavior.

**Comment by pl0301** [comment]
ok! thanks,it helps a lot

**Comment by pl0301** [comment]
one more question ,I override the didChangeWatchedFiles function, but i do not see workspace/didChangeWatchedFiles in lsp log
![image](https://github.com/user-attachments/assets/4b7d8fa1-83fc-412f-b719-d2cff2a6179e)

**Comment by pl0301** [comment]
Do I need to inherit certain classes from lsp4ij to implement it?

**Comment by angelozerr** [comment]
> one more question ,I override the didChangeWatchedFiles function,

On your language server side, right? If it that it is normal that you don't see LSP traces. It is the LSP client (LSP4IJ) which must send a notification to the language server and you will receivethe notification inside your implemented didChangeWatchedFiles 

You need to register the file watchers capability on your language server side. For instance if you install Go language server (see https://github.com/redhat-developer/lsp4ij/blob/main/docs/user-defined-ls/gopls.md), it tracks the *.go file and the language server registers the proper capability when server is started:

```
[Trace - 09:58:28] Received request 'client/registerCapability - (3)'
Params: {
  "registrations": [
    {
      "id": "workspace/didChangeWatchedFiles-0",
      "method": "workspace/didChangeWatchedFiles",
      "registerOptions": {
        "watchers": [
          {
            "globPattern": "**/*.{go,mod,sum,work}",
            "kind": 7
          },
          {
            "globPattern": "**/*.{mod,work}",
            "kind": 7
          }
        ]
      }
    }
  ]
}
```

LSP4IJ uses those pattern to send the proper notification that you will receive on your implemented function.

**Comment by pl0301** [comment]
![image](https://github.com/user-attachments/assets/8894aa87-e00a-4374-9bd2-964e7a1bd44f)
I am integrating lsp4ij into my plugin, and from the logs, I didn't find client/registerCapability.

**Comment by pl0301** [comment]
and this is response init
[Trace - 16:13:57] Received response 'initialize - (1)' in 2502ms.
Result: {
  "capabilities": {
    "textDocumentSync": 1,
    "completionProvider": {
      "resolveProvider": true,
      "triggerCharacters": [
        ":",
        "$",
        "#",
        "@"
      ],
      "completionItem": {
        "labelDetailsSupport": true
      }
    },
    "definitionProvider": true,
    "referencesProvider": true,
    "codeActionProvider": false,
    "documentFormattingProvider": true,
    "foldingRangeProvider": true,
    "declarationProvider": false,
    "executeCommandProvider": {
      "commands": [
        "cloudspec.debug"
      ]
    },
    "workspace": {
      "fileOperations": {
        "didCreate": {
          "filters": [
            {
              "pattern": {
                "glob": "**/*.cspec"
              }
            }
          ]
        },
        "didRename": {
          "filters": [
            {
              "pattern": {
                "glob": "**/*.cspec"
              }
            }
          ]
        }
      }
    }
  }
}

**Comment by angelozerr** [comment]
No it is different, fileOperation is used to create file operation like create, rename or delete files but not when file content changed.

Your language server needs to send 

```
[Trace - 09:58:28] Received request 'client/registerCapability - (3)'
Params: {
  "registrations": [
    {
      "id": "workspace/didChangeWatchedFiles-0",
      "method": "workspace/didChangeWatchedFiles",
      "registerOptions": {
        "watchers": [
          {
            "globPattern": "**/*.{go,mod,sum,work}",
            "kind": 7
          },
          {
            "globPattern": "**/*.{mod,work}",
            "kind": 7
          }
        ]
      }
    }
  ]
}
```

Please read https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#didChangeWatchedFilesRegistrationOptions

**Comment by pl0301** [comment]
I have read this specification, and my question is that according to the specification, I do not need to declare capabilities on the server. I just need to implement the method didChangeWatchedFiles(DidChangeWatchedFilesParams didChangeWatchedFilesParams). However, after implementing it, lsp4ij did not trigger the workspace.didChangeWatchedFiles request. I want to know if I missed something? Alternatively, could you tell me the core classes of lsp4ij so that I can debug?

**Comment by pl0301** [comment]
![image](https://github.com/user-attachments/assets/b89cbf90-6515-4f17-9428-0d3adb7f3ae1)
It seems I overlooked something; I need to actively register using registerCapability(). Thank you for your explanation.

**Comment by angelozerr** [comment]
> I have read this specification, and my question is that according to the specification, I do not need to declare capabilities on the server.

You need to explain to the LSP client which files (ex : **/*.go) you want to track and which kind you want to track (create, change, delete or all (7)) by sending to the client the proper glob pattern + kind.

Once you will send this capability to the client (vscode, LSP4IJ, etc), client will track any files changed and if it matches your glob pattern you will receive the proper DidChangeWatchedFilesParams  notification.

> . I want to know if I missed something? 

As I'm trying to explain you, on your language server side, you need to send 

```
[Trace - 09:58:28] Received request 'client/registerCapability - (3)'
Params: {
  "registrations": [
    {
      "id": "workspace/didChangeWatchedFiles-0",
      "method": "workspace/didChangeWatchedFiles",
      "registerOptions": {
        "watchers": [
          {
            "globPattern": "**/*.{go,mod,sum,work}",
            "kind": 7
          },
          {
            "globPattern": "**/*.{mod,work}",
            "kind": 7
          }
        ]
      }
    }
  ]
}
```

**Comment by angelozerr** [comment]
If your language server is written in Java with LSP4J, you can see how we did that with our Qute language server https://github.com/redhat-developer/quarkus-ls/blob/aaf8b581d9340eb2c1eb0cadfcaab41c200dc87b/qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/QuteCapabilityManager.java#L126

**Comment by pl0301** [comment]
Thank you! I missed a few things. I always thought that declaring capabilities on the server side was enough, but I overlooked the registerCapability method.

**Comment by angelozerr** [comment]
I close the issue since didChange is implemented correctly.
