### ISSUE TITLE
Plugin fails with "com.redhat.devtools.lsp4ij.server.CannotStartProcessException" for Dhall LSP

### ISSUE THREAD

**Issue by jakub-borusewicz** [redhat-developer/lsp4ij#513]
Error I'm getting:

```
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.io.IOException: Cannot run program "": error=2, No such file or directory
	at com.redhat.devtools.lsp4ij.server.ProcessStreamConnectionProvider.start(ProcessStreamConnectionProvider.java:68)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$0(LanguageServerWrapper.java:231)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

My configuration
![image](https://github.com/user-attachments/assets/a4a6f8ad-847d-4dab-a21f-f0961b129e64)
![image](https://github.com/user-attachments/assets/3e4fd9a2-2105-4042-9985-df2673f1e982)
![image](https://github.com/user-attachments/assets/776dc8be-33d4-4e3e-a980-94bcbce63e33)
![image](https://github.com/user-attachments/assets/267e3d0c-6905-415d-bdd7-d84170139c5d)

Any advice how to fix that? Sorry if I'm making some silly mistake with configuration, I'm new to using this plugin and LSP in general

[lsp4ij-export20240906.zip](https://github.com/user-attachments/files/16904973/lsp4ij-export20240906.zip)

**Comment by angelozerr** [comment]
Could you please export your language server configuration (see https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserDefinedLanguageServer.md#exporting-templates) and attach the generated zip to this issue.

**Comment by jakub-borusewicz** [comment]
@angelozerr done

**Comment by angelozerr** [comment]
Sorry I don't see your zip?

**Comment by jakub-borusewicz** [comment]
Attached it to original post at the bottom, here you have it also:
[lsp4ij-export20240906.zip](https://github.com/user-attachments/files/16905065/lsp4ij-export20240906.zip)

**Comment by angelozerr** [comment]
I have:

 * donwloaded the Windows assets [dhall-lsp-server-1.1.3-x86_64-Windows.zip](https://github.com/dhall-lang/dhall-haskell/releases/download/1.42.0/dhall-lsp-server-1.1.3-x86_64-Windows.zip) at https://github.com/dhall-lang/dhall-haskell/releases/tag/1.42.0
 * I have unziped in a folder
 * I have imported your export
 * update your command to execute the exe "C:\Users\USERNAME\Downloads\dhall-lsp-server-1.1.3-x86_64-Windows\bin\dhall-lsp-server.exe"
 * create a foo.dhall file 

and it is working:

![image](https://github.com/user-attachments/assets/0172a387-236d-45ac-8c98-b6dab494c596)

I can confirm that you have a problem with your command:

 * I suggest that you try to execute this command in a terminal to see if it is working
 * if it i sworking, try to add `sh -c ` before your command

**Comment by jakub-borusewicz** [comment]
After few tries I discovered that I had whitespace on the beginning of the command string :facepalm: so it's my fault
but maybe would be good idea to automatically strip whitespaces in the command box :) just an suggestion

Thanks for help!

**Comment by angelozerr** [comment]
> After few tries I discovered that I had whitespace on the beginning of the command string :facepalm: so it's my fault
> but maybe would be good idea to automatically strip whitespaces in the command box :) just an suggestion
> 

Wow it is an horrible problem!

Thanks for your feedback. We indeed fix that.

> Thanks for help!

You are welcome and hope you will enjoy with LSP4IJ

**Comment by angelozerr** [comment]
@jakub-borusewicz I have fixed your issue with spaces in https://github.com/redhat-developer/lsp4ij/pull/515

You can install [nightly-builds](https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-nightly-builds) to have this fix or wait for Monday because we will create the 0.5.0 release.
