### ISSUE TITLE
Invalid encoded URI like file://c%3A/ when dir contains '.'

### ISSUE THREAD

**Issue by zeroZshadow** [redhat-developer/lsp4ij#520]
When trying to "Go to Declaration" on something that is declared in a file listed under "External Libraries", the editor responds with `Cannot find declaration to go to`.
However when hovering over this same item, the documentation is clearly shown in the popup.

Any other "Go to Declaration" works, only those linked to things in "External Libraries" is not functioning.

I've initially filed this under the ZigBrain plugin that integrates with lsp4ij, but was forwarded here.
https://github.com/FalsePattern/ZigBrains/issues/63

**Comment by angelozerr** [comment]
@zeroZshadow could you please install the build zip that you can find at https://github.com/redhat-developer/lsp4ij/actions/runs/10827075868 (see explanation at https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-the-ci-builds to know how to install it) and tell me if it fixes your issue?

**Comment by zeroZshadow** [comment]
This fixed the issue for me. Thanks!

**Comment by angelozerr** [comment]
Thanks @zeroZshadow for having taken time to investigate the problem which helped me a lot.

I merged the PR and the fix will be available in 0.6.0 release. By waiting for this release you can install the [nightly-builds](https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-nightly-builds)
