### ISSUE TITLE
Address editor in RustRover's Memory View tab triggers LSP requests

### ISSUE THREAD

**Issue by InSyncWithFoo** [redhat-developer/lsp4ij#560]
![](https://github.com/user-attachments/assets/bfaca009-7d7d-4232-b267-74d094fb3de5)

Apparently that tiny editor is considered a Rust editor. I'm not sure if it is supposed to be one, but in any case, it shouldn't trigger LSP requests.

**Comment by angelozerr** [comment]
I have seen in some code base from intellij-community that they check if `VirtualFile `implements `VirtualFileWindow` like https://github.com/JetBrains/intellij-community/blob/513f3fa1ee2db78cf63d6f5b38fe0192deeb2861/platform/testFramework/src/com/intellij/testFramework/FileTreeAccessFilter.java#L21

I wonder if it is the case with this editor?

Is it possible for you to debug LSP4IJ to check if the  `VirtualFile `implements `VirtualFileWindow` . If it is the case, perhaps we should check that?

**Comment by angelozerr** [comment]
Another test that I have seen too is https://github.com/JetBrains/intellij-community/blob/513f3fa1ee2db78cf63d6f5b38fe0192deeb2861/platform/analysis-impl/src/com/intellij/codeInsight/completion/CompletionAssertions.java#L90 perhaps we should check if Editor doesn't implement EditorWindow? It is perhaps the case of this Rust view editor?

**Comment by angelozerr** [comment]
You have created an lsp4ij user defined language server with rust m'appelle with the rust language?

Is that?

**Comment by angelozerr** [comment]
> > Yes, I simply used the default template without any changes.
> 
> OK it will be difficult for me to undestand the problem since RustRover is not free and we have no sources.
> 

Do you know if https://github.com/intellij-rust/intellij-rust provide this same memory view?

**Comment by angelozerr** [comment]
> I take that back. There's [this `debugger` module](https://github.com/intellij-rust/intellij-rust/tree/c6657c02bb62075bf7b7ceb84d000f93dda34dc1/debugger/src/main/kotlin/org/rust/debugger).

Have you the same problem?

**Comment by angelozerr** [comment]
> I just told you I never used the plugin. Also, RustRover is free for non-commercial use.

Sorry I read your answer too quickly. I will investigate this problem when I will find time.

**Comment by angelozerr** [comment]
@InSyncWithFoo I don't know if it will fix your issue but could you please install build zip that you can download at https://github.com/redhat-developer/lsp4ij/actions/runs/11918076983

See instruction at https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-the-ci-builds

Thanks for your feedback

**Comment by angelozerr** [comment]
@InSyncWithFoo thanks for your feedback. Could you please install nighty build to check if you have the problem.

I would like to check if the PR that I did fix really the problem.

Thanks

**Comment by angelozerr** [comment]
Thanks for your feedback.

I have just some luck to discover this method and you did the test. Thats very cool.
