### ISSUE TITLE
`textDocument/didClose` is triggered upon the first close event when multiple views of the document are open

### ISSUE THREAD

**Issue by bzoracler** [redhat-developer/lsp4ij#574]
At least for the user-defined language server, when multiple views of a document are open, closing any one of them triggers a `textDocument/didClose`. I don't think this is correct.

The proper way to handle multiple open windows and `textDocument/didClose` is not explicitly described, but based on the discussion in https://github.com/microsoft/language-server-protocol/issues/285 and the specifications, it is strongly implied that `textDocument/didClose` should only trigger when the *last* view of a document is closed, rather than the first time the user closes any one of the views.

In the current behaviour in LSP4IJ,
* `textDocument/didOpen` only fires on the first time a user opens a document, not any subsequent times a user opens a new view for the document; it is therefore only possible to balance the number `textDocument/didOpen` events by triggering at most 1 `textDocument/didClose` while any views of the document is open. This is correct based on the specfication:
 
  > [`textDocument/didOpen`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didOpen)
  > An open notification must not be sent more than once without a corresponding close notification send before. This means open and close notification must be balanced and the max open count for a particular textDocument is one.

* If multiple views of a document are open, and `textDocument/didClose` triggers before all of them are closed, it is not possible to fulfil the following `textDocument/didClose` specification:

  > [`textDocument/didClose`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didClose)
  > The document’s master now exists where the document’s Uri points to (e.g. if the document’s Uri is a file Uri the master now exists on disk). As with the open notification the close notification is about managing the document’s content.

  This is because the client, at this point in time with opened views of the document, still owns the content.

Apart from triggering language server methods in `textDocument/didClose` too early, this issue also causes the language server to start shutting down when only one text document (with multiple views) is open, and you close any one of them.

**Comment by angelozerr** [comment]
> At least for the user-defined language server, when multiple views of a document are open

I dont master IntelliJ, could you explain me how you do that please (with wich menu)

**Comment by bzoracler** [comment]
There might be other ways of doing this, but I always use split views:

![image](https://github.com/user-attachments/assets/bc85e585-c5c0-42d9-86ec-85fa87088130)

Right-click the file bar for the file you want to get another view for (here, `manager.py`) to get the menu shown, then choose either `Split Right` or `Split Down`. This will open another view of the file.

**Comment by angelozerr** [comment]
Thanks @bzoracler

**Comment by angelozerr** [comment]
Please give a try to the [latest nightly build](https://plugins.jetbrains.com/plugin/23257-lsp4ij/versions/nightly), it should fix your issue, if no please reopen the issue.

The 0.7.0 will be released Tuesday, see https://github.com/redhat-developer/lsp4ij/discussions/572

**Comment by bzoracler** [comment]
Thanks for the fast response, this worked perfectly!

**Comment by angelozerr** [comment]
OK great. Thanks for having reported the issue and give me feedback.
