### ISSUE TITLE
LSP formatting error: Message could not be parsed.

### ISSUE THREAD

**Issue by He1pa** [redhat-developer/lsp4ij#579]
I got an error about Message could not be parsed.
![image](https://github.com/user-attachments/assets/af4a7628-0a09-49d4-9319-d34d5b0f6183)

How can I get more detailed error information?
Btw, this server works fine in vscode. I don't know what went wrong.

**Comment by He1pa** [comment]
In addition, it cannot be used in MacOS and Windows systems. However, except for format, other lsp features are work fine

**Comment by angelozerr** [comment]
Could you give me the link to the vscode extension which uses the language servers and if you are using user defined languzge server , could yiu export it by sélecting the server in the lsp console with contextual menu and attach the zip. Thanks.

**Comment by angelozerr** [comment]
You should see this error in the LSP console too, perhaps you will have more info?

And perhaps your LSP logs something, perhaps you have some info in Logs tab?

**Comment by He1pa** [comment]
> Could you give me the link to the vscode extension which uses the language servers and if you are using user defined languzge server , could yiu export it by sélecting the server in the lsp console with contextual menu and attach the zip. Thanks.

https://marketplace.visualstudio.com/items?itemName=kcl.kcl-vscode-extension

**Comment by He1pa** [comment]
open file - format file
![image](https://github.com/user-attachments/assets/f86296a2-dae8-4a67-9179-5c8236abc433)

**Comment by He1pa** [comment]
I think we meet an error from 
https://github.com/redhat-developer/lsp4ij/blob/67f8e683d44f268fcdc28fb11a5c41cb253b1110/src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPFormattingSupport.java#L57

or

https://github.com/redhat-developer/lsp4ij/blob/67f8e683d44f268fcdc28fb11a5c41cb253b1110/src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPFormattingSupport.java#L64

But I don't know more details.

**Comment by He1pa** [comment]
Is there any limitation when parsing TextEdit range? I used (0,0)-(u32:max, u32:max) when building Response, I guess the problem is here. After my test, it can be parsed normally when executing formmat range request (returning normal range), but it will fail when formatting the entire file (returning (0,0)-(u32:max, u32:max))

**Comment by angelozerr** [comment]
You don"t see the LSP formatting response because LSP4J (not LSP4IJ) failed when it tries to parse the JSON response from your language server https://github.com/eclipse-lsp4j/lsp4j/blob/7ce4f59bb2781094a013180f1b72bd4301d3e361/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/MessageJsonHandler.java#L133

The only solution that I see to understand the problem is to know the response of the language server, perhaps by setting a breakpoint in https://github.com/eclipse-lsp4j/lsp4j/blob/7ce4f59bb2781094a013180f1b72bd4301d3e361/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/MessageJsonHandler.java#L133

**Comment by He1pa** [comment]
> Is there any limitation when parsing TextEdit range? I used (0,0)-(u32:max, u32:max) when building Response, I guess the problem is here. After my test, it can be parsed normally when executing formmat range request (returning normal range), but it will fail when formatting the entire file (returning (0,0)-(u32:max, u32:max))

Well, I solved the problem. I set the new range to (0,0)-(u32:max, u32:max) and Gson didn't seem to parse the value correctly. I recalculated the range and everything worked fine.

**Comment by angelozerr** [comment]
>Well, I solved the problem. 

where?

**Comment by angelozerr** [comment]
Ok thanks for your feedback! That's strange that it works in vscode but not with LSP4J?
