### ISSUE TITLE
No `textDocument/didOpen` sent when server is restarted

### ISSUE THREAD

**Issue by rcjsuen** [redhat-developer/lsp4ij#585]
1. Have editors opened that target your language server.
2. Clear your traces.
3. Stop the server.
4. Restart the server.
5. Note that the traces do include `initialize` and so on but there is no `textDocument/didOpen` event sent. Given that there are editors opened (per step 1) I would have expected these events to be sent on server startup for any opened document that applies to the started language server.

```
[Trace - 07:29:40] Sending request 'shutdown - (54)'.
[Trace - 07:29:40] Received response 'shutdown - (54)' in 1ms.
[Trace - 07:29:40] Sending notification 'exit'
[Trace - 07:29:43] Sending request 'initialize - (1)'.
[Trace - 07:29:43] Sending notification 'initialized'
[Trace - 07:29:43] Received response 'initialize - (1)' in 14ms.
[Trace - 07:29:43] Sending notification 'workspace/didChangeConfiguration'
[Trace - 07:29:43] Received notification 'window/showMessage'
[Trace - 07:29:44] Received notification 'window/showMessage'
[Trace - 07:29:44] Received request 'workspace/semanticTokens/refresh - (1)'
[Trace - 07:29:44] Sending response 'workspace/semanticTokens/refresh - (1)'. Processing request took 0ms
```

**Comment by angelozerr** [comment]
Thats strange it should work like LSPE does.

**Comment by angelozerr** [comment]
You are right @rcjsuen , we need to implement that.

**Comment by angelozerr** [comment]
@rcjsuen you can install https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-nightly-builds

When you will 

* stop the ls, it should remove codelens, inlay hints and folding.
* start ls ,it should send a didOpen + refresh codelens, inlay hints and folding.

The refresh of the other features like documentSymbol, semanticTokens, etc must be implemented.

**Comment by rcjsuen** [comment]
@angelozerr It seems okay with 0.8.0-20241119-164305 based on my simple test. Thanks!
