### ISSUE TITLE
Duplicated diagonostics

### ISSUE THREAD

**Issue by onriv** [redhat-developer/lsp4ij#588]
Hi using 0.7.0 I still see duplicated diagonostics like https://github.com/redhat-developer/lsp4ij/issues/444 after registering filetype. The lsp request seems only sent once. The most weird part is that I cannot reproduce it with `runIDE`, it seems only happened in a real IDE.

![image](https://github.com/user-attachments/assets/a34347a7-d246-4588-bbae-a8bd9759409b)

**Comment by angelozerr** [comment]
Indeed I think it is the problem, but it is a nightmare because it should work with old version of IJ
