### ISSUE TITLE
Method/function completions don't (consistently?) use an insert handler with parens for args

### ISSUE THREAD

**Issue by SCWells72** [redhat-developer/lsp4ij#610]
First off, great work on this! It's going to significantly improve the lives of my own plugin's users who pair it with the free Community Edition IDEs by providing quite reasonable JS/TS/CSS support.

One thing I've noticed when playing with it is that when code completions are offered for methods and functions, it doesn't seem to use `ParenthesesInsertHandler#NO_PARAMETERS/WITH_PARAMETERS`, so the user has to add the parentheses manually. It's not a huge thing, but it's definitely a solid quality-of-life feature that makes overall typing of code so much more seamless.

I've also noticed that the signature information displayed as the completion lookup element tail text doesn't consistently show the signature. It seems to be missing at first and then fills in as I cursor up and down through the offered completions. Perhaps that's related?

Anyway, let me know if I can offer any other useful information, and thanks again for the wonderful work!

**Comment by angelozerr** [comment]
> First off, great work on this! 

Thanks!

Don't hesitate to write a review at https://plugins.jetbrains.com/plugin/23257-lsp4ij/reviews to help us to promote LSP4IJ.

>It's going to significantly improve the lives of my own plugin's users who pair it with the free Community Edition IDEs by providing quite reasonable JS/TS/CSS support.
> 
> One thing I've noticed when playing with it is that when code completions are offered for methods and functions, it doesn't seem to use `ParenthesesInsertHandler#NO_PARAMETERS/WITH_PARAMETERS`, so the user has to add the parentheses manually. It's not a huge thing, but it's definitely a solid quality-of-life feature that makes overall typing of code so much more seamless.

This feature should be managed with the language server (by using LSP snippet). Perhaps it is a configuration of the typescript language server https://github.com/typescript-language-server/typescript-language-server/blob/master/docs/configuration.md that you can configure with the LSP console https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserDefinedLanguageServer.md#configuration-tab.

> 
> I've also noticed that the signature information displayed as the completion lookup element tail text doesn't consistently show the signature. It seems to be missing at first and then fills in as I cursor up and down through the offered completions. Perhaps that's related?
> 

Same thing, those signature are managed with the language server, perhaps you can configure it?

> Anyway, let me know if I can offer any other useful information, and thanks again for the wonderful work!

Thanks!

**Comment by angelozerr** [comment]
@SCWells72 there is a bug with lsp4ij to support the case of typescript language server 

After settings the proper completionCalls settings, typescript and you open completion it generates complerion with function method name without signature. 

The method signature is generated on resolve completion like you noticed when yiu select the completion item. Lsp4ij doesnt take care of this changes when completion is applied.

I am trying to fix it.

**Comment by SCWells72** [comment]
@angelozerr, I just built the latest locally and tried method completions in TypeScript, and I'm not seeing the parameter parens being added consistently. For example, try just typing `console.lo` and accept `log(...)` as a completion. Sometimes the parens are added and the caret is placed within them, and sometimes the you just end up with `console.log<caret>`. I've tried debugging it by setting a breakpoint in `LSPCompletionProposal#updateCompletionFromResolved()`, but that causes it to work consistently, so I'm guessing it's timing-sensitive. Any ideas on what might be happening?

**Comment by angelozerr** [comment]
> Here's a good example of the behavior that I'm seeing:
> 
> ![Image](https://github.com/user-attachments/assets/2f36fac8-9d62-423a-a096-6e89dd5c07de)
> 

Thanks for the demo. Please create a new issue. The problem comes from the resolved is not done evry time.

I will study how to fix that

**Comment by SCWells72** [comment]
See #627.
