### ISSUE TITLE
Add support for Next/Previous Method by implementing `StructureViewTreeElement#getTextOffset`

### ISSUE THREAD

**Issue by SCWells72** [redhat-developer/lsp4ij#618]
While the structure view is implemented nicely based on LSP information, one key feature enabled by the structure view implementation is not, namely support for the **Next/Previous Method** actions. Those are enabled by implementing `StructureViewTreeElement#getTextOffset` to return the start offset of the associated name identifier element.

I've already implemented this on a fork/branch if you'd like for me to open a PR.

**Comment by angelozerr** [comment]
Please create a PR. I could try to review it before the release planned on tomorrow and hopefuly merge it before the release.

**Comment by SCWells72** [comment]
Done. See https://github.com/redhat-developer/lsp4ij/pull/619.
