### ISSUE TITLE
Add `gotoClassContributor` for LSP type symbols

### ISSUE THREAD

**Issue by SCWells72** [redhat-developer/lsp4ij#624]
The request should be pretty straightforward, and I have a PR ready for this one that I'll link very shortly.

**Comment by SCWells72** [comment]
See PR https://github.com/redhat-developer/lsp4ij/pull/625.

**Comment by angelozerr** [comment]
Very nice idea! We should update also the docs LSPSupport.md which speak about workspace symbols
