### ISSUE TITLE
Inserted completions for methods/functions still don't include argument parens consistently

### ISSUE THREAD

**Issue by SCWells72** [redhat-developer/lsp4ij#627]
This is effectively a follow-up to #610, specifically the behavior demonstrated here after the fix for that issue was implemented:

https://github.com/redhat-developer/lsp4ij/issues/610#issuecomment-2498640289

Hopefully that provides what's needed. Please let me know if not.

**Comment by angelozerr** [comment]
I reopen the issue because there are some bugs again.

**Comment by SCWells72** [comment]
> [@SCWells72](https://github.com/SCWells72) your issue should be fixed now.

It's definitely improved. There are still some lingering unexpected behaviors, but I don't know if they can be addressed. For example, sometimes the tail text still isn't displayed for the initial selected completion, and without that, the signature isn't added to the inserted completion. A quick cursor down/up "fixes" that, but I have a feeling that will be needed more often than expected/desired.

Additionally, methods/constructors/functions that are imported don't work, e.g.

![Image](https://github.com/user-attachments/assets/1ef403d6-9804-4c4e-adb8-15edbd2efc41)

yields just `refreshApex` instead of `refreshApex(<args>)`. As you can see, that's listed as an alias to the imported function instead of the imported function itself, so perhaps that's just a limitation of the TypeScript language server?

**Comment by SCWells72** [comment]
Verbose/trace logging didn't include anything useful, but setting a breakpoint in `LSPCompletionProposal#handleInsert` did show the fundamental issue, and it does appear to be with the TypeScript LSP response.

Here's the (abridged) `CompletionItem` for a non-imported method:

```
item = ...
 label = "log"
 kind = {CompletionItemKind@70981} "Method"
 detail = "(method) Console.log(...data: any[]): void (+1 overload)"
 documentation = {Either@70983} "Either [\r\n  left = null\r\n  right = MarkupContent [\n  kind = "markdown"\n  value = "[MDN Reference](https://developer.mozilla.org/docs/Web/API/console/log_static)"\n]\r\n]"
 sortText = "11"
 insertText = "log($1)$0"
 insertTextFormat = {InsertTextFormat@70986} "Snippet"
```

and here's the same for an imported function (which is the same as for a method):

```
item = ...
 label = "areEqual"
 kind = {CompletionItemKind@70805} "Variable"
 detail = "(alias) function areEqual(number1: number, number2: number): boolean\nimport areEqual"
 documentation = {Either@70807} "Either [\r\n  left = null\r\n  right = MarkupContent [\n  kind = "markdown"\n  value = "Checks two floating point values for equivalence.\n\n*@param* `number1` — the first value  \n\n*@param* `number2` — the second value  \n\n*@return* — `true` if the two values are equivalent; otherwise `false`"\n]\r\n]"
 sortText = "11"
 insertText = null
 insertTextFormat = null
```

Obviously the difference is in the missing `insertText` and `insertTextFormat`. I'll dig a bit and see if perhaps there's a TypeScript language server config option to report those as deferenced instead of as the alias.

**Comment by angelozerr** [comment]
> Verbose/trace logging didn't include anything useful, 

You should use LSP console https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserGuide.md#lsp-console Perhaps you have not saved the config?

but setting a breakpoint in `LSPCompletionProposal#handleInsert` did show the fundamental issue, and it does appear to be with the TypeScript LSP response.
> 
> Here's the (abridged) `CompletionItem` for a non-imported method:
> 
> ```
> item = ...
>  label = "log"
>  kind = {CompletionItemKind@70981} "Method"
>  detail = "(method) Console.log(...data: any[]): void (+1 overload)"
>  documentation = {Either@70983} "Either [\r\n  left = null\r\n  right = MarkupContent [\n  kind = "markdown"\n  value = "[MDN Reference](https://developer.mozilla.org/docs/Web/API/console/log_static)"\n]\r\n]"
>  sortText = "11"
>  insertText = "log($1)$0"
>  insertTextFormat = {InsertTextFormat@70986} "Snippet"
> ```
> 
> and here's the same for an imported function (which is the same as for a method):
> 
> ```
> item = ...
>  label = "areEqual"
>  kind = {CompletionItemKind@70805} "Variable"
>  detail = "(alias) function areEqual(number1: number, number2: number): boolean\nimport areEqual"
>  documentation = {Either@70807} "Either [\r\n  left = null\r\n  right = MarkupContent [\n  kind = "markdown"\n  value = "Checks two floating point values for equivalence.\n\n*@param* `number1` — the first value  \n\n*@param* `number2` — the second value  \n\n*@return* — `true` if the two values are equivalent; otherwise `false`"\n]\r\n]"
>  sortText = "11"
>  insertText = null
>  insertTextFormat = null
> ```
> 
> Obviously the difference is in the missing `insertText` and `insertTextFormat`. I'll dig a bit and see if perhaps there's a TypeScript language server config option to report those as deferenced instead of as the alias.
