### ISSUE TITLE
Add first-class support for Go To Implementation(s) / Type definitions

### ISSUE THREAD

**Issue by SCWells72** [redhat-developer/lsp4ij#636]
This is an offshoot of #628 where we discussed how there is currently only a custom action for Go To Implementation instead of the IDE's native action. I've implemented support for that and want to start a PR to see whether or not it might be accepted.

**Comment by SCWells72** [comment]
See https://github.com/redhat-developer/lsp4ij/pull/637.

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/lsp4ij/pull/637
