### ISSUE TITLE
Create tests for LSP selection range

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/lsp4ij#675]
Once https://github.com/redhat-developer/lsp4ij/pull/669 will be merged it whould be nice to write tests

@SCWells72 are you interested to work on it?

**Comment by SCWells72** [comment]
@angelozerr, yes, of course. That's part of the work required to make it whole. Please feel free to assign this to me.

**Comment by SCWells72** [comment]
I've added tests in the context of #669 since it's still open.

**Comment by SCWells72** [comment]
@angelozerr I think this can be closed now since #669 has been merged and it included these tests.

**Comment by angelozerr** [comment]
Thanks @SCWells72

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/lsp4ij/pull/669
