### ISSUE TITLE
Diagnostic severity should default to ERROR instead of INFO when severity is not specified

### ISSUE THREAD

**Issue by cherylking** [redhat-developer/lsp4ij#88]
This [code](https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_redhat-2Ddeveloper_lsp4ij_blob_1213d4b8bc4b4a2aaf7603a9d507c91712165ed1_src_main_java_com_redhat_devtools_lsp4ij_operations_diagnostics_SeverityMapping.java-23L41&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=TdmXKMyPId3d0ZeMKZnk7puRw1g1iLAGcvVBh8N6H6k&m=DZhgseJBPMK6AydSrA2cmTpvlDdxn_kD1pg72qElhqCzptq7Q2y-6I8duXw34czL&s=wylmKI8bO8OIvHjyO2MyHqI44g_Zc-9qVNN9JgqJDYo&e=) is setting the severity to INFO if it is not specified. It should be set to ERROR to align with vscode behavior according to @angelozerr comment [here](https://github.com/OpenLiberty/liberty-language-server/issues/260#issuecomment-1875000289).

**Comment by angelozerr** [comment]
It has been fixed in https://github.com/redhat-developer/lsp4ij/pull/66

Please see main branch https://github.com/redhat-developer/lsp4ij/blob/6927714f8f2be016656eed9f4cd6d587a143f804/src/main/java/com/redhat/devtools/lsp4ij/operations/diagnostics/SeverityMapping.java#L41
